### ISSUE TITLE
Inter font is not fully being displayed in Word

### ISSUE THREAD

**Issue by joaogdesigner** [rsms/inter#125]
I installed the inter font family and it's displayed across Adobe applications or other software, but it's not showing up in Word or other Office apps. I'm on Windows 10. I've read on internet that Office displays fonts with some styles "hidden" in bold or italic buttons/commands since Office apps "mix" them, differently from Adobe or other graphic software which shows them up as individual styles, however I don't know if that's the case.

**Comment by rsms** [comment]
Please use the "bug report" issue template when submitting a new issue.

https://github.com/rsms/inter/issues/new?template=bug_report.md

We need a lot more information in order to be able to help.

Thank you.

**Comment by LoganDark** [comment]
@rsms They have most of the info, they just didn't use the Obligatory Super-Strict Bug Reporting Format. Here's the OSSBRF filled out using information from the post.

**Describe the bug**
Inter doesn't display in the font selector

**To Reproduce**
Steps to reproduce the behavior:
1. In Microsoft Word
2. Try to change the font
3. Inter is not in the list/dropdown

**Expected behavior**
Inter should be selectable and usable as a font

**Screenshots**
(No screenshots)

**Environment**
- OS: [e.g. macOS 10.14] Windows 10
- App that renders the font [if applicable; e.g. Chrome, Adobe Illustrator] Microsoft Word
- Version of font [e.g. "Inter Regular 3.0;8cf05e4a" — you can use fontdrop.info to find out the version] Not sure which one, but I'm pretty sure OP _just_ installed the latest version and found this issue.

**Additional context**
(Nope)

**Comment by LoganDark** [comment]
@joaogdesigner Try answering these 3 questions:
- What's your Windows 10 build and arch (32/64-bit)?
- What version of Office do you have?
- What font version did you use?

then you should be all set.

**Comment by joaogdesigner** [comment]
@LoganDark as you may see, I'm a designer and, although I'm a professional in the digital market, I don't know every process, every tool, every site, every bureaucracy etc., so I'm not familiar with this github thing. I appreciate your help, but the font's owner don't wanna facilitate. I gave more info than any common user would give, and it was not enough. I'm on Win 10 64, update 1809, version 10.0.17763, build 17763, Office 365 subscription, Inter font v3.3, gigabyte motherboard b75m-d3h, 10GB ram, corsair case, UEFI bios mode, a WD SSD 240GB, timezone America_SaoPaulo GMT -02:00.

I'm gonna use San Francisco Text or Helvetica, it's less difficult.

**Comment by LoganDark** [comment]
I understand, @rsms completely refused to cooperate. You did provide the required information, but I doubt they'd accept it now. Good luck. SF Text is a great font. I'd also recommend [Output](https://djr.com/output/) as a UI font. They offer personal licenses for free if you contact them.

**Comment by joaogdesigner** [comment]
@LoganDark people who launch "open source" things think that because it's open source I'm gonna lose my mind to them. I will give a look at Output. Thanks again for helping me effectively.

**Comment by LoganDark** [comment]
You're welcome. I'd rather not be too rude to the maintainer as this is a great font, but their social skills need work.

**Comment by joaogdesigner** [comment]
To me, great products only are great if the customer service is great, and that methodology works very well in my life, with everything. The audience is there for us when some superpower staff comes up to show off the superpowers they actually don't have. I live in Brazil, the country where the customer service is a total fail, and I'm not gonna deal if more failures outside here.
