### ISSUE TITLE
Odd Spacing in Chrome

### ISSUE THREAD

**Issue by tmswr** [rsms/inter#131]
Chrome displays font with odd spacing. I've tried every featuring setting combination imaginable, but the issue is still there. 

1. Display Inter UI using hosted CSS file
2. Set font for use
3. Odd spacing is displayed (Chrome Only)

![image](https://user-images.githubusercontent.com/44615905/52967364-7a6f1f00-336f-11e9-8103-34b6fa3dbe6e.png)

**Environment**
- OS: Windows 10
- Chrome
- https://rsms.me/inter/font-files/Inter-upright.var.woff2?v=3.3

**Comment by ruslanegorov** [comment]
This only happens with variable font

**Comment by rsms** [comment]
This is **due to a bug in Chrome with variable fonts.** The issue can be observed on mac as well, although ClearType on Windows amplifies the issues.

Here are screenshots from Windows 10 on Chrome, Firefox and Edge using static/constant fonts and variable fonts. Note how only the variable font on Chrome is poorly displayed—the same variable font in other browsers is rendered correctly.

Chrome static/const vs variable:
![a1-chrome](https://user-images.githubusercontent.com/47046/55294879-038c6380-53bc-11e9-8fa2-4986c8c3586a.PNG)
![a2-chrome-vf](https://user-images.githubusercontent.com/47046/55294880-08e9ae00-53bc-11e9-942e-b65fc31b0c87.PNG)

Edge static/const vs variable:
![a3-edge-const](https://user-images.githubusercontent.com/47046/55294881-08e9ae00-53bc-11e9-9929-45efba9fe900.PNG)
![a3-edge-vf](https://user-images.githubusercontent.com/47046/55294882-08e9ae00-53bc-11e9-88b1-937853268f71.PNG)

Firefox static/const vs variable:
![a5-ff-const](https://user-images.githubusercontent.com/47046/55294884-08e9ae00-53bc-11e9-8388-d521097474e0.PNG)
![a4-ff-vf](https://user-images.githubusercontent.com/47046/55294883-08e9ae00-53bc-11e9-945c-ee761e84bb3b.PNG)

**Comment by rsms** [comment]
See https://bugs.chromium.org/p/chromium/issues/list?can=2&q=variable+component%3ABlink%3EFonts for a list of variable-font related issues in Chrome/Chromium
