### ISSUE TITLE
Light weights

### ISSUE THREAD

**Issue by jahala** [rsms/inter#14]
Beautiful font!
Any chance for "Light" and "Thin" versions? 
(Even though they may be outside of the current scope of the font)

**Comment by rsms** [comment]
This is definitely on the roadmap. Big project though and probably best done in a parallel branch.

**Comment by lisabufzinski1671** [comment]
Can take out

**Comment by timHau** [comment]
What is the current status of this Issue?
Would like to help if possible

**Comment by pjrvs** [comment]
I'd love a thin/light version too 👍

**Comment by linuz90** [comment]
Eagerly waiting for at least a Light variations as well. Loving this typeface 🙌

**Comment by JulianKingman** [comment]
This would be awesome.

**Comment by n0mar** [comment]
Any updates? 😊

**Comment by rsms** [comment]
Thank you all for chiming in!

This is a side project that I do on my free time. Adding a light weight means creating a new master by hand, which essentially means drawing over 2000 glyphs (Inter UI has a little over 2300 glyphs.) Including kerning.

Something like this probably takes around 300 hours.
Say I can find four full days every month to work on this (8 hours a day of productive work), then it would take about 9 months to complete.

Now add the fact that I try to have a life, am working at a startup and have other hobby projects, it's not likely that this will happen until end of 2019.

_**However**_ there are _shortcuts we could take._ For instance, I could extrapolate a thin weight from the existing masters as a starting point, and we would have lighter weights in a matter or hours rather than months, but most glyphs would look like crap. Over time, glyph by glyph would be manually redrawn and the quality would gradually improve.

The latter is probably the best approach :–)

**Comment by rsms** [comment]
Started this today and took the "shortcut" approach as mentioned above. About 10 hours in and I've gotten farther than I thought I would. About 2–3% or so I'd say.

Glyphs drawn so far:
<img width="1249" alt="screen shot 2018-11-25 at 17 28 27" src="https://user-images.githubusercontent.com/47046/48987998-bdef1f80-f0d7-11e8-9130-5d92e60f9565.png">

And here's a view of what the glyphs generated via extrapolation looks like — pretty f-ed with all sorts of issues, but they do serve as a good starting point for drawing new glyphs.
<img width="1579" alt="screen shot 2018-11-25 at 17 28 13" src="https://user-images.githubusercontent.com/47046/48988018-dcedb180-f0d7-11e8-9ed6-a68ae729b134.png">

I'll post an early build in a little while.

**Comment by rsms** [comment]
Here's a build with this past weekend's work:

[Inter-UI-3.2-light-dcec705b07.zip](https://github.com/rsms/inter/files/2616554/Inter-UI-3.2-light-dcec705b07.zip)

How far I got:

<img width="751" alt="screen shot 2018-11-26 at 08 53 43" src="https://user-images.githubusercontent.com/47046/49029194-e23f1080-f158-11e8-9ebf-835710338efe.png">

**Comment by rsms** [comment]
Work is happening in the "light" branch https://github.com/rsms/inter/tree/light

**Comment by rsms** [comment]
Progress update
<img width="812" alt="screen shot 2018-11-30 at 00 19 35" src="https://user-images.githubusercontent.com/47046/49277226-c75cec80-f435-11e8-85aa-b2ea6a0650ea.png">

**Comment by rsms** [comment]
![jkzfhaflafjasd](https://user-images.githubusercontent.com/47046/49277777-a0071f00-f437-11e8-9ceb-93bc70651773.gif)

**Comment by renatocarvalho** [comment]
Beeeautiful!

**Comment by rsms** [comment]
I've been very busy with life and work recently and haven't been able to make more progress, but will have time in the next few weeks to get back to this.

**Comment by rsms** [comment]
A few more samples of work in progress.

<img width="1118" alt="screen shot 2018-12-25 at 18 01 56" src="https://user-images.githubusercontent.com/47046/50428612-506d1500-0876-11e9-9e0d-ae4e9a92311f.png">
<img width="860" alt="screen shot 2018-12-25 at 18 30 46" src="https://user-images.githubusercontent.com/47046/50428614-52cf6f00-0876-11e9-9bb9-3f0f97ddcf72.png">

**Comment by rsms** [comment]
Some more screenshots of work in progress

<img width="886" alt="screen shot 2018-12-27 at 15 16 44" src="https://user-images.githubusercontent.com/47046/50499032-357bdb80-0a03-11e9-9f49-14d781490106.png">
<img width="1112" alt="screen shot 2018-12-27 at 15 46 53" src="https://user-images.githubusercontent.com/47046/50499034-3ad92600-0a03-11e9-8082-37e30e9fafa3.png">
<img width="1174" alt="screen shot 2018-12-27 at 16 37 29" src="https://user-images.githubusercontent.com/47046/50499036-3d3b8000-0a03-11e9-9818-73d7f908905c.png">
<img width="1207" alt="screen shot 2018-12-27 at 18 13 37" src="https://user-images.githubusercontent.com/47046/50499037-3f054380-0a03-11e9-96e1-6ab6fb5501d9.png">

**Comment by rsms** [comment]
Here's a new pre-release beta build:

[Inter-UI-3.2-light-9bb34a8fa6.zip](https://github.com/rsms/inter/files/2713744/Inter-UI-3.2-light-9bb34a8fa6.zip)

**Comment by renatocarvalho** [comment]
@rsms Thank you!

**Comment by rsms** [comment]
<img width="1122" alt="screen shot 2018-12-29 at 11 57 44" src="https://user-images.githubusercontent.com/47046/50541347-fd8aaa80-0b60-11e9-91b6-aa526b4e0f02.png">

**Comment by rsms** [comment]
Here's a new build of the latest progress:
[Inter-UI-3.2-light-b82b74e544.zip](https://github.com/rsms/inter/files/2716826/Inter-UI-3.2-light-b82b74e544.zip)

Some screenshots of changes since past screenshots above:
<img width="950" alt="screen shot 2018-12-29 at 14 19 04" src="https://user-images.githubusercontent.com/47046/50543312-eca65d00-0b91-11e9-8484-d6b4662484f3.png">
<img width="1083" alt="screen shot 2018-12-29 at 15 02 32" src="https://user-images.githubusercontent.com/47046/50543314-f5972e80-0b91-11e9-8708-f2aedf55035b.png">
<img width="1051" alt="screen shot 2018-12-29 at 17 29 50" src="https://user-images.githubusercontent.com/47046/50543315-f8921f00-0b91-11e9-95d9-3972388ea409.png">

**Comment by rsms** [comment]
New beta build:
[Inter-UI-3.2-light-889f6cf3be.zip](https://github.com/rsms/inter/files/2719095/Inter-UI-3.2-light-889f6cf3be.zip)

Mainly diacritics

**Comment by rsms** [comment]
The "light" branch has been merged into master. Dist builds produce zip archives with the lighter weights, with font files marked by "-BETA".

**Comment by rsms** [comment]
Light, Extra Light and Thin (300, 200, and 100 weight classes, correspondingly) are now included in official releases marked as "BETA", starting with [release v3.2](https://github.com/rsms/inter/releases/tag/v3.2)
