### ISSUE TITLE
Inter variable doesn't currently show as multiple weights in MS Word

### ISSUE THREAD

**Issue by thundernixon** [rsms/inter#142]
**Describe the bug**

In builds of the latest version of Inter, the upright variable font doesn't display multiple instances in Microsoft Word, as variable fonts should:

![image](https://user-images.githubusercontent.com/7355414/54788069-312b1d00-4c04-11e9-8cba-6e5ea535bace.png)

Environment:

**To Reproduce**
1. Build Inter Variable
2. Load into Windows 10
3. Access in Word

**Expected behavior**
A variable font's named instances should appear in the MS Word font menu as multiple, separate fonts.

**Environment**
- Windows 10 (VMWare Fusion)
- MS Word v 1901 (Office 365)
- Inter Variable 3.4 at https://github.com/rsms/inter/commit/20aaab681df22c8251fbc1bb68fbd38a1b858b32

**Additional context**

This is probably fixable with [gftools fix-vf-meta](https://github.com/googlefonts/gftools/blob/master/bin/gftools-fix-vf-meta.py). I'll try this and close the issue if so.

**Comment by rsms** [comment]
70f3df78824523be229b74c80a9deb4964b1412c adds gftools "fix-vf-meta" as a post-processing step to zip distributions. Since it modifies the files, and requires multiple file inputs, it's tricky to integrate into Make, which is why it as added as a post-processing step.

"fix-vf-meta" only supports single-axis VF at the moment, so the affected files are:

- Inter-upright.var.woff2
- Inter-italic.var.woff2
- Inter-upright.var.ttf
- Inter-italic.var.ttf

I've attached the result from `make zip` here:
[Inter-3.4-35a23627a5.zip](https://github.com/rsms/inter/files/3014719/Inter-3.4-35a23627a5.zip)

Since I don't have Microsoft Office (Word) on my Windows machine, it would be great if you could test this, @thundernixon :–)

**Comment by thundernixon** [comment]
😶 I should have realized that `fix-vf-meta` that was all that was needed. Nice work! It's better to have it in the build, anyway. In fact, it might make sense to also include `fix-gasp` and `fix-dsig`, as I've also put these into my QA `move-check` script, but they would make more sense in a build flow. Then again, I'm less certain of the benefit of these vs `fix-vf-meta`, so it may not be as important.

Good news: the weight-axis-only variable fonts now work in MS Word!

![image](https://user-images.githubusercontent.com/7355414/55105673-75ef0200-50a3-11e9-9ec4-4e5ee74cd097.png)

Style-linking (Regular to Bold) also works well.

Note: the font names are sorting in a slightly unintuitive way (alphabetical, by name), but this is a more general problem with Word and variable fonts, and not something we've found a way to fix on the font side. So, this issue is closed!

**Comment by apollolux** [comment]
Hello! I just attempted to install a variable version of Inter 3.11 and am getting this issue with the non-single axis files. Also, for some reason Win10 isn't letting me install both the roman and italic single axis files at the same time, but that's probably a slightly different issue.

I encountered this issue with tonsky/FiraCode#770 , almost certainly due to the build process, and the workaround for that seemed to be to export it directly from Glyphs rather than fonttools/mkfont/whatever since it seems the build tool isn't properly setting the instance names in the final file.
