### ISSUE TITLE
Weird leading of @ if placed between a number/special char and a lowercase letter (no space)

### ISSUE THREAD

**Issue by ericamigo** [rsms/inter#149]
**Describe the bug**
I noticed this one when typing email address like root1@mail.com. the @ symbol moves a bit downward only if place it between a number or special character to its left and a lowercase letter.

**Steps to reproduce the behavior**
1. 1@2
2. a@b
3. a@1
4. 1@A
5. A@1
6. %@1
7. #@A 
8. &@a
9. 1@a

Numbers 8 and 9 - @ symbol moves a bit downward (#8 - its a small letter 'a' - why its keeps tagging a person? lol)

**Environment**
- Windows 10
- Chrome, Firefox (tried it on ms edge but i cant reproduce the issue)
- Font Version: 3.4

**Comment by rsms** [comment]
This is by design.

The /at glyph is positioned slightly higher when _surrounded by_ (not just adjacent to) capital letters and many other cap-height tall glyph. You can disable contextual alternates in the application you're using (if you're using HTML, it will be `font-feature-settings: 'calt' 0`)

See also:

- https://rsms.me/inter/#features/calt
- https://rsms.me/inter/lab/?sample=Feature%3A%20calt
