### ISSUE TITLE
Incorrect font rendering when using color in rgba

### ISSUE THREAD

**Issue by fivemru** [rsms/inter#151]
**Describe the bug**
Incorrect font rendering when using color in rgba with small font size and transparency.

**To Reproduce**
1. Set the font size to 12px
2. Set the color in `color: rgba(0,0,0,0.3);`

**Expected behavior**
Clear text rendering.

**Screenshots**
![2019-04-05_011820](https://user-images.githubusercontent.com/30273470/55593064-42ffda80-5743-11e9-850b-65d78727d476.png)

**Environment**
- OS: windows 10
- Chrome Version 73.0.3683.86 (Official Build) (64-bit)
- Inter Regular. Version 3.005;git-f04932174 

**Additional context**
The problem was discovered after updating the Figma application.
The application uses color with transparency.
Below are a few links to problem reports.
[comment 1](https://spectrum.chat/figma/announcements/we-refreshed-figmas-ui~fa767089-1921-44b2-88ab-9f2cd5eaafec?m=MTU1NDM5OTk4NjUyMA==)
[comment 2](https://spectrum.chat/figma/announcements/we-refreshed-figmas-ui~fa767089-1921-44b2-88ab-9f2cd5eaafec?m=MTU1NDQwMDkwMDg4Mg==)
[comment 3](https://spectrum.chat/figma/announcements/we-refreshed-figmas-ui~fa767089-1921-44b2-88ab-9f2cd5eaafec?m=MTU1NDQxNDEwNjU1MQ==)
[comment 4](https://spectrum.chat/figma/announcements/we-refreshed-figmas-ui~fa767089-1921-44b2-88ab-9f2cd5eaafec?m=MTU1NDQxNjk5OTE2MQ==)

**Comment by rsms** [comment]
This is unfortunately how Chrome works on Windows and has nothing to do with this typeface.

The really really short version of what's going on: Subpixel anti-aliasing causes "fattened" text normally but is disabled for any text that is transparent or partakes in a transform without a solid background (since SPAA relies on knowing the background color.)

You could try using the hinted font files on Windows which helps Window ClearType with drawing sharper letterforms.
