### ISSUE TITLE
Inter UI > Inter issue in Figma

### ISSUE THREAD

**Issue by itsnwa** [rsms/inter#153]
**Describe the bug**
I updated from the old Inter UI to Inter, but Figma is still showing Inter UI + Inter..
Inter UI works fine, but Inter does not.. Switching between weights does nothing, it's like it's stuck on one weight. While in Adobe, the font list is showing Inter only, which is correct.

Not sure if this is an Inter bug, or a Figma bug?

**To Reproduce**
1. Use Inter UI
2. Delete Inter UI and Install newest version of Inter
3. Open Figma and use Inter

**Expected behavior**
Inter UI should be removed from my system, and Inter should be the only font showing up in my font lists.

**Environment**
- OS: macOS 10.14.5 Beta
- Adobe Photoshop, Adobe Illustrator, Figma
- Inter 3.5

**Additional context**
I'm using RightFont to manage my fonts, and I've tried to delete all traces of Inter from the library and from the `~/Library/Fonts` folder, re-install and reboot - no luck.. 😔

**Comment by rsms** [comment]
This might be a Figma issue as I'm unable to reproduce this myself.
Best path forward is to write in to Figma support using the little question mark:
<img width="56" alt="Screen Shot 2019-04-23 at 16 30 42" src="https://user-images.githubusercontent.com/47046/56622475-2a1d7300-65e5-11e9-82c1-0fc649b944c4.png">

I'm assuming that after step 3 you still _only_ see "Inter UI" but _not_ "Inter" in the font family list (it's not clear from your comment what happens after step 3.)

Note that "Inter UI" is provided automatically by Figma and will show up no matter if you have it installed locally or not. (Though if you do have it locally installed, your local version will be used by Figma rather than the version provided by Figma itself.)

My best guess is that this is what is going on — you keep seeing both "Inter UI" and "Inter". This is expected. You can quickly replace the font of all text objects by selecting one text object and searching for "select all with same font" in the main menu of Figma, then changing the font family to "Inter".

**Comment by itsnwa** [comment]
Ah, I see, I didn't know that Figma had the Inter UI in the font list.

Sorry for not clarifying the steps properly, but this is what happens in Figma when I try to use Inter:

![Screen Recording 2019-04-24 at 18 48 50](https://user-images.githubusercontent.com/19958806/56678032-0c720b80-66c2-11e9-9fbb-9601faa5e487.gif)

As you can see, it seems like Inter is not loaded when selected.
I'll try Figma support 🙏🏼

**Comment by city17** [comment]
> Ah, I see, I didn't know that Figma had the Inter UI in the font list.
> 
> Sorry for not clarifying the steps properly, but this is what happens in Figma when I try to use Inter:
> 
> ![Screen Recording 2019-04-24 at 18 48 50](https://user-images.githubusercontent.com/19958806/56678032-0c720b80-66c2-11e9-9fbb-9601faa5e487.gif)
> 
> As you can see, it seems like Inter is not loaded when selected.
> I'll try Figma support 🙏🏼

Did you manage to solve this? I'm running into the same problem..

**Comment by garrettqmartin8** [comment]
@city17 I ran into this. My issue was having Inter Variable installed on my system. I uninstalled that, re-installed all the separate Inter font weights, and the problem went away.

**Comment by Flashwalker** [comment]
Same shit.

**Comment by rsms** [comment]
Figma does not support variable fonts, so yeah, make sure to install the constant font files. Variable font support is spotty, generally and there are lots of bugs in various software related to variable fonts, so it's strongly recommended to install constant font files in your OS'es font repository. There's a "Inter-V" variable font in the Inter release zip which has a different family name which you can install alongside regular Inter in order to test variable fonts.

**Comment by Flashwalker** [comment]
I found that desktop .ttf **Inter** font doesn't works. Weights ignored.  
Removing from system solves the issue.
