### ISSUE TITLE
Characters at size 10 look very condensed and mushed together.

### ISSUE THREAD

**Issue by Derpitron** [rsms/inter#166]
**Describe the bug**
When attempting to change the font size in any program, like Notepad++ for example, the size 10 seems to be very narrow, almost like a condensed font.

**To Reproduce**
1. Open a program like Notepad++, or in my case, the MultiMC Minecraft Launcher, and go to the font settings.
2. If possible, like in the MultiMC log font settings, you can change the font size, then alternate it between 9, 10, and 11.
3. Compared to 11 and even 9, 10 seems to be very condensed

**Expected behavior**
The font scales consistently, despite rasterization (which doesn't happen at 10, strangely enough).

**Screenshots**
[https://gyazo.com/f7464ccf7bc9d8749cd751174180758d](A link to the gif I took in MultiMC settings)

**Environment**
- OS: Windows 10 (Happens regardless of version, but for reference, 1903.)
- App that renders the font: Chrome, MultiMC, Notepad++, Adobe XD
- Version of font: Inter 3.6

**Comment by thundernixon** [comment]
@Derpitron this is most likely due to the way hinting operates with Windows ClearType.

To keep the strokes of letters as crisp and legible as possible, fonts often have hinting instructions that nudge points to better align to the pixel grid. At certain point sizes, this gives the appearance of letters "jumping" slightly in size. Typically, things hinted with TTFautohint "jump up," with the logic that it is better to give the interior spaces of letters more space rather than less. Put another way, the alternative to the size 10 looking tall is A) for the font to have no hinting, or B) for size 10 to round down in size, and look short. 

The variable versions of Inter don't have hinting, so you could simply install those on your computer. Especially if you have a fairly high-DPI monitor, fonts will probably look fine with no hinting. There are a few other issues with variable fonts right now because they are somewhat new, however, so you may or may not prefer them.

**Comment by rsms** [comment]
Thank you for an excellent explanation @thundernixon :–)
