### ISSUE TITLE
VF: Consider negating slant angle

### ISSUE THREAD

**Issue by rsms** [rsms/inter#175]
See https://github.com/rsms/inter/pull/172

- Per the OpenType spec, `slnt` should use a negative value for text that slants left-to-right (forward). Inter currently uses positive values for forward slant.
- However, changing slnt to negative values causes both Chrome and Safari to stop understanding oblique as outlined here: https://github.com/rsms/inter/pull/172#issuecomment-513287264

TODO:
1. Investigate further if there are some open bugs in Chromium related to slnt-oblique-italic mapping
2. Consider using "ital" axis instead of "slnt" axis — there may be differences/bugs in the implementation of Safari, Chrome, et al
3. Consider reverting the `italicAngle` change introduced by e45e2e518abfe029950a15146e84709aa8075a21 and sticking with positive angles as it seems to work correctly in practice.

**Comment by thundernixon** [comment]
Just a question to clarify:

In the tests using `font-style: oblique 10deg`, did you run this on a font with a `slnt` value of `0` to `-10`, or `0` to `10`? It seems like you only ran tests which matched positive with positive and negative with negative.

Going by the specs, things should be like this for forward-slanting styles:
- In the font, the `sltn` axis and `italicAngle` should be negative 
- In the CSS, the angle should be positive in the `font-style: oblique __deg`

The CSS working group acknowledges that these values are opposite, here:
https://drafts.csswg.org/css-fonts-4/#font-style-prop

> Note: the OpenType slnt axis is defined with a positive angle meaning a counter-clockwise slant, the opposite direction to CSS. The CSS implementation will take this into account when using variations to produce oblique faces.

Looking at your tests today, they seem to be missing one that follows both specs: 
- a `slnt` of `-10` in the font
- a `font-style` with `oblique 10deg` in the CSS

Would you be willing to run that and share the results? I'm guessing you still have that test webpage around somewhere, so hopefully it's a quick task.

**Comment by thundernixon** [comment]
My guess is, it won't work as it should, based on [my own experiments](https://codepen.io/thundernixon/full/ormaav).

![image](https://user-images.githubusercontent.com/7355414/61582451-4e5ff180-aaf9-11e9-810d-a920c8715924.png)

![image](https://user-images.githubusercontent.com/7355414/61582464-68013900-aaf9-11e9-856d-1c34265bb63f.png)

**Comment by thundernixon** [comment]
As for this point:

> Consider using "ital" axis instead of "slnt" axis

It's a pretty good idea! The `slnt` axis [doesn't really follow exact degree angles perfectly](https://twitter.com/axis_praxis/status/1083183293368029184) anyway, and [ital goes from 0 to 1](https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_slnt), which is more intuitive than the negative values of `slnt`. I wanted to test this approach in my own project. 

Unfortunately, it's buggy in its own ways.

Whether I use `font-style: oblique 0deg 15deg;` or `font-style: oblique 0deg -15deg;` or ` font-style: normal italic;` in my `@font-face`, I get the following results.

---

**Safari:** `font-style: italic` does turn on italic alternates as I want (a GSUB rule is working), but it appears to both add the italic angle from my font, _plus_ its own synthetic additional 15deg slant.

![image](https://user-images.githubusercontent.com/7355414/61583223-12318e80-ab03-11e9-9344-59d5133b0ed9.png)

---

**Chrome:** doesn't apply `ital` axis at all.

![image](https://user-images.githubusercontent.com/7355414/61583252-70f70800-ab03-11e9-9878-528082467f87.png)

---

**Firefox:** the closest to rendering as expected. Applies the proper `ital` slant, with the forms as drawn rather than with synthetic slant. Doesn't cue my `ital`-linked GSUB alternates, however.

![image](https://user-images.githubusercontent.com/7355414/61583224-16f64280-ab03-11e9-86ec-467b0fd4cbae.png)

---

It may be confusing that I'm adding another variable here for `CRSV` (cursive). This simply allows that italic alternates to be always-off, auto-on (controlled by `ital` axis), or always-on.

![Kapture 2019-07-20 at 15 39 11](https://user-images.githubusercontent.com/7355414/61583324-a0f2db00-ab04-11e9-8abf-d2ff3cdb9715.gif)

So, `font-style: italic;` _should_ turn `ital` to `1`, which would slant my font to 15° and activate cursive alternates. But, that's not happening yet.

I'd be curious to see whether things are any different in Inter, but I think this is probably something we'll need to file as a bug report with browser vendors.
