### ISSUE TITLE
Rename variable font

### ISSUE THREAD

**Issue by fnky** [rsms/inter#208]
When you try to install Inter Variable Fonts, and already have the normal font files installed, they will conflict due to the naming of the font.

This means that you'll have to delete the previous font files in order to install the variable font files and vice versa. It's quite inconvenient when you wan't to use the normal font for some projects and variable font for others.

A way to fix this would be to give variable fonts a different name like `Inter VF` / `Inter Italic VF` or similar, so that they can be installed alongside the normal files.

**Comment by rsms** [comment]
I’ve been wanting to do this for a while. Thanks for filing it!
Next release will ship with a variable font that uses a different family name.

However, the trade-offs here are important to recognize:

Say you are working together with other people on something (e.g. InDesign document, Figma design, Photoshop image, etc.) and you have the “Inter VF” family installed but your coworker has “Inter” installed. No software will know that these are the same and thus you and your coworker will constantly have font conflicts.

The hope with variable fonts is that they become the norm and standard, rather than an exotic thing, just like how OTF took over from the Type-1 font format. For this reason, the variable fonts of inter are still named “Inter”.

The next release will include an _additional_ set of variable font files with a different name, to be used for dual installations only.

**Comment by fnky** [comment]
> Say you are working together with other people on something (e.g. InDesign document, Figma design, Photoshop image, etc.) and you have the “Inter VF” family installed but your coworker has “Inter” installed. No software will know that these are the same and thus you and your coworker will constantly have font conflicts.

Seeing as variable fonts are still at early stages of adoption, the current naming scheme causes even more conflicts as both variable fonts and static fonts with the same name could also cause inconsistencies;

For example, if I use a variable font with custom variables, that cannot be reflected in the static font, it will cause the fonts to be different and possibly overridden. Depending on how the software handles these kinds of conflicts, this would be a less enjoyable experience.

**Comment by rsms** [comment]
Added in
- bc8b267b01d4652334e6f4a5452e77fbf79b329d
- 0ba7c2b42f06dd2ded8cdeca8563dadf089f1d14
- ba71122abf9a4ad2deb8bfb31a95edc2495cc839

Next release will include an additional variable font with the family name “Inter V”.
