### ISSUE TITLE
Ligature for "fi" and "fl"

### ISSUE THREAD

**Issue by dnlsndr** [rsms/inter#256]
It would be nice to have a ligature for "fi" and "fl" which I think would help with legibility in long texts.
Maybe it was an stylistic decision to not implement it, but it would be nice to have an option to enable it with stylistic sets or character variants, to give the font even more personality.

Image of such a ligature:
![149px-Ligature_drawing svg](https://user-images.githubusercontent.com/23470589/78472394-92069400-7738-11ea-9955-7fc9fa919780.png)

**Comment by rsms** [comment]
Since Inter is meant to have its letter spacing adjusted, to be tracked, depending on optical size, ligatures are tricky as many layout engines and shapers will disable ligatures as soon as there is _any_ letter spacing adjustments while a few good (IMHO) layout engines out there retains ligatures within a small range of letter-space adjustments. Inter was designed to work well without ligatures (and there are many more than fi, ffi, fl etc.)

I will keep this open for consideration but I’d like to set the expectations right here: It is unlikely this will happen.

**Comment by onmyflow** [comment]
Thanks for the explaination!

**Comment by TaigaYamada** [comment]
Now fi & ffi ligatures are implemented in 4.0

**Comment by dnlsndr** [comment]
Awesome, thanks for the update!
