### ISSUE TITLE
Missing U+2154 Fraction Two Thirds 2/3

### ISSUE THREAD

**Issue by silomia** [rsms/inter#258]
Hello,
We find the most common fractions: ½ ¼ ¾ ⅓ ⅛ ⅜ ⅝ ⅞ but, surprisingly, ⅔ (Unicode U+2154) is missing. As ⅓ is here, ⅔ should be there also.
Can you please add it for a next release?
Below, ⅔ is replaced by a system font:
![two-third-missing](https://user-images.githubusercontent.com/57560151/79021699-870a9400-7b7c-11ea-9d76-a574a143c4af.png)
Thank you.

**Comment by rsms** [comment]
I’ll consider it. Inter intentionally only implements the most common fractions as dedicated glyphs and then [provides a `frac` feature](https://rsms.me/inter/#features/frac) for composing almost any imaginable fractions.

**Comment by thebertian** [comment]
The argument of most common fractions omitting 2/3 doesn't make sense to me. Including the full range of /2, /4, and /8 denominators and excluding the obscure 1/7, 1/9, and 1/10 glyphs makes sense. Including 1/3 but excluding 2/3, and including 5/6 but excluding 1/6 seems inconsistent.

Granted, not many font faces include the U+215x range. Among some on PC that do, Arial includes the /3 and /8 denominators; Calibri, Cambria Math, and Consolas /3 /5 /6 /8; and Segoe UI and Times New Roman the whole range. But none includes only the partial range of a denominator.

[MDN shows broad support for CSS property font-feature-settings](https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings), so using `frac` works fine for web. The problem I foresee is when choosing which glyph to publish when designing for a font-stack or text expected to be copied to another program. 1/3 and 2/3 wouldn't maintain uniformity because of the way they have to be expressed.

**Comment by rsms** [comment]
Implemented since version 4.0
