### ISSUE TITLE
U+041A CYRILLIC CAPITAL LETTER KA is inconsistent

### ISSUE THREAD

**Issue by sk1nzz** [rsms/inter#279]
Glyph name: Kacyr
Unicode: U+041A CYRILLIC CAPITAL LETTER KA
The glyph looks incorrect in weights 200-600.
It should look like this:
![Frame 4](https://user-images.githubusercontent.com/32013220/81680688-8a878880-9464-11ea-936f-dbb455b40170.png)

**Comment by VladWinner** [comment]
I confirm this issue (v3.19). The current implementation is incorrect. Instead, the letter `U+041A` should look the same as in these fonts:
![image](https://user-images.githubusercontent.com/13555921/122620684-44a3e780-d09c-11eb-8391-50483bcd7874.png)

**Comment by VladWinner** [comment]
@rsms I've done a bit of research.
![image](https://user-images.githubusercontent.com/13555921/122784904-8bbbf380-d2bb-11eb-9f19-ea44b15ac4a7.png)

In the latest build (v3.19) the only valid KA-based letter (where `<`-connection is not broken): Kaverticalstrokecyrillic `U+049C`
### Solution:
Revert KA-based glyphs
- Kacyr `U+041A`
-  kacyrillic `U+043A`

to [v2.3](https://github.com/rsms/inter/releases/tag/v2.3) design.

Maybe you could directly use this glyphs from v2.3, with conditions:
-  Kacyr `U+041A` — after increasing horizontal line width to latest build:
![image](https://user-images.githubusercontent.com/13555921/122783126-f3713f00-d2b9-11eb-9009-4785aabec693.png)
_↑ This is a illustrative example and does not show final offset values (see PT Root UI or Golos UI fonts as a reference)_

- kacyrillic `U+043A` — after correction this glyph line to the same width:
![image](https://user-images.githubusercontent.com/13555921/122781244-4944e780-d2b8-11eb-985f-3052616fdc97.png)

Also adjust the glyphs according to these changes:
Kadescendercyrillic `U+049A`
Kahookcyrillic `U+04C3`
Kabashkircyrillic `U+04A0`
kabashkircyrillic `U+04A1`
kadescendercyrillic `U+049B`
kahookcyrillic `U+04C4`
kaverticalstrokecyrillic `U+049D`
kjecyrillic `U+045C`

Also note that kappa symbol `U+03BA` **should not** duplicate _Cyrillic_ Ka `U+041A` as seen in latest release
![image](https://user-images.githubusercontent.com/13555921/122786620-2b2db600-d2bd-11eb-8312-1b058dcb1bf9.png)

**Comment by VladWinner** [comment]
And one more addition:

1) I found a font where the similar (current) implementation of letter `к` from Inter font is used (here two diagonal lines come out of horizontal connection line asymmetrically too), but as you can see, this is definitely not a typeface designed for user interfaces. In this screenshot I'm showing an Cyrillic font that is used for street navigation signs (for a specific city) and ability to text recognition from a long distance (when driving), but when viewed up close, because of its specificity, it demonstrates a local flavor stylization details to passers-by.
![image](https://user-images.githubusercontent.com/13555921/124332947-7c7e5500-db9b-11eb-8f1b-9fafe3fc7db1.png)
![image](https://user-images.githubusercontent.com/13555921/124333815-f1eb2500-db9d-11eb-94c9-b9a974af4df6.png)

2) I also show Lab screenshot with Inter in comparison to "HarmonyOS Sans" as one of the last released typeface for user interfaces with small-medium text:
![image](https://user-images.githubusercontent.com/13555921/124334770-d46b8a80-dba0-11eb-99c8-159db4ea1bba.png)

**Comment by Derpitron** [comment]
Hi, I am beginning to edit letter Ka.
Does this look according to your expectations? (weight:400)

**Upright**
![image](https://user-images.githubusercontent.com/46134462/149868707-0b50d032-3b63-4de1-ae4d-5087473dff6c.png) 
**Italic**
![image](https://user-images.githubusercontent.com/46134462/149868767-68d56d3f-7985-4d3c-a06a-527f7ac37b86.png)

**Comment by Derpitron** [comment]
Hello, I have made a branch of my Inter font fork dedicated to patches and bugfixes, and I have attempted to rectify these issues in both Inter Text and Inter Display families. The commit in question is derpitron/inter@4d24d4f90e09f97f1caeeaa8e3bb6fc34aad590e

**Comment by rsms** [comment]
Thank you @Derpitron for fixing this in #423
