### ISSUE TITLE
Improved Elfdalian support

### ISSUE THREAD

**Issue by u8is** [rsms/inter#285]
Elfdalian is a language spoken in the Älvdalen region of Sweden.
Inter already supports Swedish, Icelandic, and several languages that use letters with the ogonek, which together cover most of Elfdalian.
What's missing is Y with ogonek (Y̨, y̨) and Å with ogonek (Ą̊, ą̊).
The full alphabet is as follows:

> A Ą B C D Ð E Ę F G H I Į J K L M N O P Q R S T U Ų V W X Y Y̨ Z Å Ą̊ Ä Ö
> a ą b c d ð e ę f g h i į j k l m n o p q r s t u ų v w x y y̨ z å ą̊ ä ö

And (at least on KDE) the currently missing letters look pretty bad. :)

**Comment by rsms** [comment]
Being Swedish, we of course have to make this happen!
Tackar & bockar!

**Comment by fjallarefur** [comment]
Underbart!
To my knowledge, that would make Inter the first open source font with good Elfdalian support.
Not even Noto handles it well.

**Comment by Derpitron** [comment]
@rsms slowly reveals more and more of himself in these comments on issues.. >:D

**Comment by rsms** [comment]
Looking into this today I found that there are no Unicode code points assigned to these glyphs; they are purely compositions i.e. "y̨" is U+0079 & U+0328 ("y" followed by combining ogonek.) The best I could do is to introduce a ligature for this pair.

See:
- https://en.wikipedia.org/wiki/Ogonek
- https://en.wikipedia.org/wiki/Latin_Extended-A

**Comment by rsms** [comment]
Okay, here's where I ended up, adding six new specialized glyphs which do not have unicode mappings but are instead triggered by OpenType ccmp (glyph composition.)

- /Aringogonek for A + ring + ogonek
- /aringogonek for a + ring + ogonek
- /Aringogonek for Aogonek + ringnosp
- /Yogonek for Y + ogoneknosp
- /yogonek for y + ogoneknosp
- /aringogonek for aogonek + ringnosp
<img width="868" alt="Screen Shot 2020-08-17 at 14 37 26" src="https://user-images.githubusercontent.com/47046/90446978-33163b80-e097-11ea-845d-1c25e339759d.png">

**Comment by rsms** [comment]
The "y̨" was tricky as the configuration varies when sampling images of prints. Some fonts have really elaborate lettershapes where the bottom tail of the "y" splits in two, like a really integrated special ogonek, while others have a regular ogonek that's attached and some have a regular ogonek that's separate. The latter ended up feeling more readable and I saw more modern designs using this approach. The caveat is that the heavier weights have a customized ogonek that is more of a teardrop shape as the heavy weights otherwise has a relatively thick ogonek.
<img width="1083" alt="Screen Shot 2020-08-17 at 14 43 53" src="https://user-images.githubusercontent.com/47046/90447408-18909200-e098-11ea-92b7-e6efe3f21338.png">

**Comment by rsms** [comment]
This has now been released as part of [version 3.14](https://github.com/rsms/inter/releases/tag/v3.14) 🎉

**Comment by moyogo** [comment]
The ogonek should attach to the letter in Elfdalian.
The issue with looking at other fonts, is that it’s not clear which one what designed with Elfdalian in mind.

Here’s how it looks in Råðdjärum, Älvdalska språkrådet, 2005, [*Förslag till en enhetlig stavning för älvdalska*](http://www.ulumdalska.se/wp-content/uploads/2017/10/alvdalsk_ortografi.pdf):
<img width="158" alt="image" src="https://user-images.githubusercontent.com/1923747/90471948-af546180-e11f-11ea-8297-1527105f1b95.png">

<img width="84" alt="image" src="https://user-images.githubusercontent.com/1923747/90471089-8632d180-e11d-11ea-99c5-da80fea186d4.png">

Here is a sample from Yair Sapir and Gunnar Nyström, 2015, [Introduktion till älvdalska](http://hkr.diva-portal.org/smash/record.jsf?pid=diva2%3A807822&dswid=-5271):
<img width="140" alt="image" src="https://user-images.githubusercontent.com/1923747/90471169-bf6b4180-e11d-11ea-89ee-8eab68479a69.png">

While these are not perfect, they do show the ogonek attached. For context, Yair Sapir was consulted by Råðdjärum, Älvdalska språkrådet when 2005 orthography was created and Gunnar Nyström was part of that committee.
Your second design would probably be the best:
<img width="127" alt="image" src="https://user-images.githubusercontent.com/1923747/90471342-428c9780-e11e-11ea-9bbb-1bca19197307.png">

I did find an example with the ogonek detached from (http://www.ulumdalska.se/2018/12/nu-ar-den-pa-vag/) but the ogonek is between two letters, closer to the second letter, so this seems like an error.
<img width="171" alt="image" src="https://user-images.githubusercontent.com/1923747/90473966-84b8d780-e124-11ea-8cce-fda0427f69b3.png">

Since the first two samples come from good sources, it seems the ogonek should be placed just below the baseline and attached to the y.
It would be better to contact an Elfdalian expert to be sure what is preferred.

**Comment by u8is** [comment]
I am not an expert either.
I have two Elfdalian books, and they both use the "split" y̨.
I've attached a photo of what it looks like in Älvdalsk Grammatik by Bengt Åkerberg and Gunnar Nyström.
**Dialekt Uni** is the typeface used in this book, but the website for it is unavailable at the moment.
![image](https://user-images.githubusercontent.com/42881386/90525342-73e18380-e16f-11ea-9a31-106d28463faa.png)

**Comment by rsms** [comment]
This is really helpful. Thank you.

**Comment by moyogo** [comment]
> Looking into this today I found that there are no Unicode code points assigned to these glyphs; they are purely compositions i.e. "y̨" is U+0079 & U+0328 ("y" followed by combining ogonek.) The best I could do is to introduce a ligature for this pair.

The recommended design for y-ogonek does need its own glyph, but the design you had made or the Y-ogonek didn’t.
Glyphs.app or fontmake will generate the mark feature that font shapers will use to position the combining ogonek on the y with the "ogonek" and "_ogonek" anchors. There are plenty of letters used in various orthographies that a shaped this way. It is not necessary to have single glyphs for all of them.
That said, if you have a yogonek with its own outline instead of components, it may be more practical to have a Yogonek for other features, even if it is a composite glyph.

**Comment by rsms** [comment]
@moyogo I've spent an incredible amount of time trying to make anchors like "ogonek" & "_ogonek" work and end up in the final font file. We're talking over a week in total of time, like multiple weekends. I gave it another go this morning, spend 3 hours testing everything I could think of. Debugged with four different font tools to be sure and tested in multiple apps on both macOS and Windows 10. I've also compiled font files using four different compilers.

Simple repro, with [fontmake](https://github.com/googlefonts/fontmake): (using fontmake to reduce the surface area of issues, e.g. with Inter's own build system)
1. `git checkout 206f684bfae76f693e4809d4a98832d826bb32e3` (this contains a patch that causes all anchors to be included in the UFO)
2. Generate UFO from the glyphs source: `make build/ufo/Inter-Regular.ufo`
3. Install fontmake: `pip install fontmake`
4. `fontmake -u build/ufo/Inter-Regular.ufo --output-path Inter-Regular-fontmake.ttf`
5. Inspect the resulting file `Inter-Regular-fontmake.ttf` in FontForge or any other font file debugger that support full parsing (note that Glyphs.app does not)

I _think_ that what is happening is `ufo2ft` being "smart" and converting anchors into mark and mkmk OT features.

**Comment by moyogo** [comment]
Indeed that is what is happening.
Fontmake uses ufo2ft’s MarkFeatureWriter to writer the mark and mkmk features if there are anchor in the UFOs.
You can use fontmake’s `--debug-feature-file` parameter to see what feature file is generated and used.

The mark and mkmk features add support to a large number of language orthographies that use accented letters that didn’t make it in time before Unicode stopped encoding composed accented letters as single characters.

Beside Elfdalian’s y-ogonek, there are many examples like G̃ g̃  used in Guarani in Paraguay, N̈ n̈ used in Malagasy, Ɛ̈ ɛ̈ used in Dinka-Nuer, Ɔ́ ɔ́ used in Lingala, Ẹ́ ẹ́ used in Yoruba, etc.
The advantage of having a mark feature for every possible base glyph + mark glyph combination is that it is future proof. If there’s a combination you didn’t think of, you won’t need to add it or modify it unless it’s a special case.

Glyphs.app also propagate anchors, for example it copies the bottom and ogonek anchors from A to Aacute. Fontmake’s MarkFeatureWriter doesn’t, but the glyphs2ufo --propagate-anchors argument or ufo2ft’s PropagateAnchorsFilter can be used for this.

That said there’s an issue with the MarkFeatureWriter and PropagateAnchorsFilter when a spacing mark has anchors and is used in composite glyphs instead of the equivalent non-spacing mark.
For example, Inter has /acute with anchors, /acutecomb as a composite of /acute, and /aacute as a composite using /acute instead of /acutecomb.
The MarkFeatureWriter will put /acute in the mark feature and in the GDEF mark glyph class since it has anchors, which means font shapers will make it non-spacing and position it on base glyphs that have matching anchors.
One possible fix is to remove the anchors from /acute, put them in /acutecomb instead, use /acutecomb in composite glyphs instead of /acute.

And of course, that fix creates another issue: nested components. In theory nested components are great, in practice some TrueType/OpenType implemenations, like some printers, fail to handle them correctly. Luckily, ufo2ft has a FlattenComponentsFilter, which can turn nested components (aacute using acutecomb using acute) into flat components (aacute using acute) but at build time and after the PropagateAnchorsFilter has done its job.

**Comment by rsms** [comment]
Thank you @moyogo, very helpful information!

**Comment by rsms** [comment]
I've done a few more takes on /yogonek. It's really tricky to make it legible at small (text) sizes with the detailed attached ogonek/tail. Here are three versions at small sizes:
<img width="440" alt="Screen Shot 2020-08-19 at 16 19 19" src="https://user-images.githubusercontent.com/47046/90699294-c1292800-e237-11ea-9a19-790d1d26ea1d.png">

**Comment by rsms** [comment]
<img width="1070" alt="Screen Shot 2020-08-19 at 16 32 28" src="https://user-images.githubusercontent.com/47046/90700031-9b9d1e00-e239-11ea-99e1-8d0c33494601.png">

(no idea if"tjy̨tter" is a word, by the way :–)

**Comment by rsms** [comment]
Here's a pre-release build with the above adjustments:
[Inter-3.15-text-f7924a233e.zip](https://github.com/rsms/inter/files/5104419/Inter-3.15-text-f7924a233e.zip)

**Comment by moyogo** [comment]
@rsms Interesting solution :-)

**Comment by rsms** [comment]
This has now been released as part of [version 3.15](https://github.com/rsms/inter/releases/tag/v3.15) 🎉
