### ISSUE TITLE
.otf files in "Inter Desktop" directory work strangely?

### ISSUE THREAD

**Issue by eckless** [rsms/inter#315]
Bug (I think): If I look at the fonts in the "Inter Desktop" directory, they have some weird behavior in Windows - for the sizes 60 and above, it uses Inter...below 60, it's replacing with something else (guessing Arial). It does this for all of the fonts in "Inter Desktop" - but doesn't do it in the other directories ("Inter Hinted for Windows", etc.).

If I run the fonts in "Inter Desktop" through the fontsquirrel "opentype flattener" tool at https://www.fontsquirrel.com/tools/webfont-generator, the resultant fonts are fine. So this may be a font issue, it may be a Windows issue.

1. Installed the font from https://rsms.me/inter/
2. Opened fonts in Windows

![inter font change](https://user-images.githubusercontent.com/70455821/91648263-dddd1100-ea2a-11ea-8c2c-53615e2b011a.jpg)

- OS: Windows
- App that renders the font: Native Windows font viewer
- Version of font 3.015;git-7f5c04026

I really do like the font - it's my preference for Windows UI replacement...thank you!

**Comment by rsms** [comment]
Wow, that is really strange. What exact version of Windows do you use?

**Comment by eckless** [comment]
It's Windows 10 Pro
Version 2004
OS build 19041.508

Thank you!

**Comment by rsms** [comment]
Interesting. I can reproduce on Windows 10 Pro with the OTF files. My guess is that Windows struggles with CFF OTF font data, which is what Inter uses for OTF. When you give that font to fontsquirrel, they convert all vector graphics to TTF curves which is why it works. If you install the TTF fonts on Windows instead it should look good. Use the folder called "Inter Hinted for Windows".

Repro with OTF on Windows 10
<img width="1280" alt="Screen Shot 2020-09-15 at 08 56 48" src="https://user-images.githubusercontent.com/47046/93234990-d52a5180-f731-11ea-9b52-625c6a2d3939.png">

Looks good when I install the TTF fonts instead
<img width="1270" alt="Screen Shot 2020-09-15 at 08 53 47" src="https://user-images.githubusercontent.com/47046/93235024-e07d7d00-f731-11ea-832b-2eb228d90d92.png">

Notes: This UI refuses to accept OTF fonts. Trying to drag and drop an otf file on the big surface shows an "x" cursor and nothing happens. This may be an indication of some issue or some limitation in Windows.
<img width="1027" alt="Screen Shot 2020-09-15 at 08 56 36" src="https://user-images.githubusercontent.com/47046/93235184-0dca2b00-f732-11ea-8cac-3fdb6835ed41.png">

**Comment by rsms** [comment]
I mean, clearly Windows is able to parse and correctly render OTF CFF since size 48 and upwards is correct so this may be a bug in Windows or a bug with that specific app that shows the preview. If I install the OTF file, I can correctly use it elsewhere including the modern font manager in Windows settings:
<img width="763" alt="Screen Shot 2020-09-15 at 09 03 24" src="https://user-images.githubusercontent.com/47046/93235424-6699c380-f732-11ea-9c99-b69e6144591a.png">

So, I'm pretty sure this mean that there's an issue with that older font preview app.

@eckless after installing the OTF, do you have issues in other apps with the font?

**Comment by rsms** [comment]
Here is some text in WordPad, first with the TTF font installed:
<img width="534" alt="Screen Shot 2020-09-15 at 09 10 23" src="https://user-images.githubusercontent.com/47046/93236189-5b936300-f733-11ea-8b10-76f3af9450d7.png">

And now, after uninstalling the TTF and installing the OTF font:
<img width="569" alt="Screen Shot 2020-09-15 at 09 09 19" src="https://user-images.githubusercontent.com/47046/93236215-64843480-f733-11ea-8376-e3f55b94d4c4.png">

Essentially identical results. Rendering is really poor but this is generally true in Windows (unfortunately.)

Rendering in Edge is much better:
<img width="138" alt="Screen Shot 2020-09-15 at 09 17 16" src="https://user-images.githubusercontent.com/47046/93237028-65699600-f734-11ea-93f1-900394bfc632.png">

<https://codepen.io/rsms/full/NWNBdMb>

```html
<html lang="en">
<head><meta charset="utf-8"></head>
<body style="font-family: 'Inter ExtraLight';font-size: 16px;">
<h1 style="font-weight:100">Rag123</h1>
<h2 style="font-weight:100">Rag123</h2>
<h3 style="font-weight:100">Rag123</h3>
<p>Rag123</p>
</body></html>
```

**Comment by rsms** [comment]
@eckless let me know if you think this is an issue beyond just the old font preview app in Windows and we can reopen the investigation. To me, it seems to work fine everywhere except in that app.

It may be so that Inter's OTF fonts contains some data that stumbles that app, but it would be almost impossible for me to debug that. It would be better if someone at Windows working on fonts would do the debugging, as whatever QA font tools I run on the inter fonts (which are produces by fonttools which is the most popular font compiler) there are no issues.
