### ISSUE TITLE
[QUESTION] Rationale for only one capital R design?

### ISSUE THREAD

**Issue by apollolux** [rsms/inter#324]
Hello! I'm more curious than I am requesting a feature about how the decision was originally made to have only one design, straight-legged, for capital R in Inter. Issues like #152 have already asked about inclusion of a curved leg R alternate, so I won't duplicate them for now.

What motivated using a straight-legged R as the default design, and was a curved leg R considered during the initial design phases? Was looking too close to Helvetica or Univers vs looking too close to Akzidenz Grotesk a concern for any letter's design? If Inter were to implement a curved leg R alternate how might it do so to integrate well with the font design as a whole, Arial/Monotype Grotesque style, Helvetica/Univers style, or other?

**Comment by inferno986return** [comment]
If if was to speculate I would say legibility, particularly at small sizes. 

This would also explain why the original Google Roboto had a curved-tailed "R" but the 2014 redrawing didn't. Same with other typefaces such as Apple San Francisco (which Inter closely resembles) and DIN 1451. Although saying this Segoe UI does have a curved leg, though perhaps it gets away with this as it protrudes diagonally rather than vertically?

As for a curved "R" I was expecting one that follows a Helvetica style like much of Inter. I would be interesting in different mockups of this.

What do you think?

**Comment by rsms** [comment]
Inter has its own personality. If we were to add any imaginable alternate representation of all glyphs, what would Inter even be? Also, the font files would be huge. The idea is for Inter—as with most typefaces—to provide a cohesive and clear personality. The font does have some alternate glyphs, like single-storey "a" and lower-case L with tail, though in those cases the reasons are either legibility (i.e. how to tell `I` and `l` apart) or a different common representation where there is not clear consensus (i.e. single-storey  "a" or sharp s aka German double-s)

The reason a straight-legged R was chosen is to match the austere style of the typeface's design and to make it easier to distinguish "R" from "B" and similar letters at small sizes.
