### ISSUE TITLE
Hyphen renders at different height

### ISSUE THREAD

**Issue by fson4** [rsms/inter#342]
Hello, the hyphen/dash renders at different height on upper and lower case letters

![Inter-dash](https://user-images.githubusercontent.com/64836011/103419818-f30eab80-4b94-11eb-8152-c384a1f4f906.png)

**Comment by fson4** [comment]
![Inter-comp](https://user-images.githubusercontent.com/64836011/103423470-117da280-4ba7-11eb-8937-338a98bd6ac9.png)

**Comment by kenmcd** [comment]
Inter supports the OpenType Case Sensitive Forms (`case`) feature which shifts certain characters up a bit when used with uppercase letters. SF Pro Text also has this feature.
This feature `case` is Off by default and must be enabled to use it.
To be helpful, Inter also does this for you automatically using the Contextual Alternates (`calt`) feature (which is On by default). It sees the hyphen/dash is next to uppercase characters (the context) and it moves the dash up for you. 
If you do not want that to happen you must disable `calt` on that text.
So this is expected behavior.

**Comment by fson4** [comment]
@kenmcd
Thank you for pointing this out to me. I'm closing this.
