### ISSUE TITLE
Vertical align issue with the latest Inter font version (rsms CDN)

### ISSUE THREAD

**Issue by pricop** [rsms/inter#361]
Hello,

I've recently noticed an issue with the way Inter is being rendered when loaded via https://rsms.me/inter/inter.css CDN.

For some reason, the text now appears slightly raised, I'm presuming this is an issue either with the line height and/or vertical align, but I'm no expert - this immediately caught my eye as we've been using Inter for a long time, and now our entire UI appears "raised" pretty much everywhere.

- [Google Fonts vs. Rsms comparison](https://i.imgur.com/OzYdgQw.png
)
- [Zoomed in view](https://i.imgur.com/NKnHXzJ.png) - this one clearly shows the text is raised.

I was able to reproduce this on Codepen too:

- Rsms source: https://codepen.io/pricop/pen/rNjMPwx
- Google fonts source: https://codepen.io/pricop/pen/eYgdxvN

I was able to reproduce this issue on multiple machines:

- Windows 10 (latest version) using Chrome 89 @ 1920 x 1080 (1:1).
- MacOS Big Sur 11.0.1 using Safari 14.0.1 @ 1920 x 1080 (1:1).

L.E. I've noticed that the font has been recently updated. I've looked at a screen-shot I've took on March 27th, 2021, and this issue was not present - the font has been updated 2 days ago. Google does not seem to serve the latest font version, while rsms does it - that's probably why the font renders okay using the Google's source.

**Comment by rsms** [comment]
Inter 3.16 introduced a number of changes to its metadata which is likely what is causing the height shift. Anyhow, looking at the HTML/CSS you provided it looks like you're using a multiple line height of 1.5 which is never going to be accurate. Your HTML/CSS simply accidentally gave you the right look! In web browsers, a multiple for `line-height` is a multiple of the font size. I.e. these are equivalent: `line-height: 1.2` and `line-height: calc(1em * 1.2)`. Now, different web browsers will round the result of that multiplication in different ways. Most browsers will round to dp (CSS "pixels"; not actual pixels.) This means that (in CSS) `font-size:14px` (which is what you're using in your HTML) multiplied by 1.5 `= 21px`, which is an odd number which means that an even bounding box can not fulfill vertical centering without fractions.

Your culprit:
<img width="299" alt="Screen Shot 2021-03-30 at 09 07 08" src="https://user-images.githubusercontent.com/47046/113021389-61352100-9138-11eb-86f8-cec3a294e11d.png">

One way to fix it:
<img width="616" alt="Screen Shot 2021-03-30 at 09 15 20" src="https://user-images.githubusercontent.com/47046/113021468-7742e180-9138-11eb-9afa-41e2fed5d8fe.png">

I know typography on the web platform is a little complicated so don't feel bad about this :-)

By the way, the fonts from Google Fonts are of an older version that had different metadata which is why the alignment ends up different there.

I'm going to keep this issue open though since there's an open decision to be made on my end of either adjust metadata so that Inter end up looking exactly the same as old versions or move forward and accept the change.

**Comment by pricop** [comment]
Hello rsms,

Thank you for having a look into this.

This issue isn't specific to our project.

The line height is what **Boostrap** and **Tailwind** use by default. Convincing these major CSS frameworks to change their defaults won't be an easy task. Sure, I could customize our project to use a different line-height, but it would change the way our design looks. 

Here's another example from Tailwind UI components: [Screenshot](https://i.imgur.com/UYBHoea.png) - as you can see, there's various elements that now look offset. This is because they're also defaulting to 1.5rem/em for their line-height.

The default fonts from MacOS (San Francisco) and Windows (Segoe UI) are aligned just fine, would love to see this change reverted so that Inter is in line with this, at least for now.

**Comment by pricop** [comment]
Just a quick update as I've done more extensive testing.

This issue does not happen only on odd numbers, it happens on even numbers too. The Codepen demo I've provided has a button that has a line height of 1.5, meaning the line-height would translate to 24 pixels, but the font is still miss-aligned, if you quickly switch tabs using your keyboard's shortcut, you should see the difference.

To demonstrate this, please see the following screenshots (try quick switching your tabs in your browsers using keyboard shortcuts, the issues should be easier to spot):

- [old font @ 1x dpi - good](https://i.imgur.com/PsZXXKQ.png)
- [new font @1x dpi - bad](https://i.imgur.com/Ym7nWTK.png)

Furthermore, the issue appears to be even more proeminent on high dpi screens.

- [old font @ 2x dpi - good](https://i.imgur.com/utqJqPX.png)
- [new font @ 2x dpi - bad](https://i.imgur.com/00u8jRF.png)

I'm not sure how fonts metadata works, but perhaps you could exclude your changes for the fonts rendered in browsers, if that's an option.

**Comment by rsms** [comment]
Hm, interesting. @pricop thanks for looking into this. (BTW, you can drop images into the GitHub comment editor to embed them :–)

Here's a quick generator for a few font sizes & line heights:
<https://codepen.io/rsms/pen/WNRRXYr>
<img width="660" alt="Screen Shot 2021-03-31 at 14 10 19" src="https://user-images.githubusercontent.com/47046/113211839-dda82c80-922a-11eb-944f-ba041f759147.png">

Indeed 14/16 is not centered (screenshot from Safari 14)
<img width="1461" alt="Screen Shot 2021-03-31 at 14 12 19" src="https://user-images.githubusercontent.com/47046/113212079-28c23f80-922b-11eb-930c-99ddd566c8fe.png">

**Comment by rsms** [comment]
Here's a build with some adjustment made to ascender and descender metrics. @pricop would you mind trying these font files out (the woff2 ones) and see if that works for you? (It does on my end.)
[Inter-3.17-text-b80228e35d.zip](https://github.com/rsms/inter/files/6239707/Inter-3.17-text-b80228e35d.zip)

**Comment by rsms** [comment]
I've added a visualization feature to the lab on the website for testing vertical alignment.
Example: <https://rsms.me/inter/lab/?draw-sample-bg=1&lineHeight=24&sample=Mj3&size=16>

this is the current release:
<img width="427" alt="Screen Shot 2021-03-31 at 14 55 10" src="https://user-images.githubusercontent.com/47046/113216421-324ea600-9231-11eb-8022-6011c3c23ca4.png">

adjusted build: (zip archive [posted earlier](https://github.com/rsms/inter/issues/361#issuecomment-811484572))
<img width="372" alt="Screen Shot 2021-03-31 at 14 56 41" src="https://user-images.githubusercontent.com/47046/113216509-5316fb80-9231-11eb-994b-382782d034c1.png">

**Comment by pricop** [comment]
Thank you for looking into this so promptly @rsms.

I've loaded the new build trough the inter.css file you provided, and everything looks as before now.

**Comment by rsms** [comment]
Here's a more complete survey of v3.17 vs changes landed in 4ab4b1d3b0b9d6480072b89cc89bf4079f9a3da5
<img width="2054" alt="Screen Shot 2021-03-31 at 15 18 13" src="https://user-images.githubusercontent.com/47046/113218531-8909af00-9234-11eb-91a4-8e692e690414.png">

**Comment by rsms** [comment]
Thank you so much for all your help @pricop!

**Comment by pricop** [comment]
With welcome, glad to see that I could help. I love the improvements you did on odd numbers too. Can't wait to see it action 👍.

**Comment by rsms** [comment]
[Released with v3.18](https://github.com/rsms/inter/releases/tag/v3.18)
