### ISSUE TITLE
Bullet ‘•’ symbol vertical-alignment mismatch if more that 5 of them are used

### ISSUE THREAD

**Issue by ashishsumann** [rsms/inter#381]
**Describe the bug**
Bullet (•) symbol vertical-alignment mismatch when we have more that 5 of them consecutively, followed by digit or capital letter.

**To Reproduce**
1. Go to inter site https://rsms.me/inter/
2. Enter at-least 6 bullet-symbols (•) followed by a capital alphabet to digit, eg `•••••••1`
3. Observe the height difference between the 5th-last and 6th-last bullet symbols

**Expected behavior**
They should be aligned properly.

**Screenshots**
![Screenshot 2021-06-08 at 4 46 40 PM](https://user-images.githubusercontent.com/81148902/121175840-2870a100-c879-11eb-9d32-26789233822c.png)

**Environment**
- OS: All
- App that renders the font: All
- Version of font: Latest

**Additional context**
This can be observed with dash (-) symbol aswell.

**Comment by rsms** [comment]
This intended behavior, or rather an intentional compromise. AFAIK there's no way to make the left-hand side cascade infinitely with OT substitutions, so the way Inter does this is by having a fixed number of searches. Having too many would slow down text shapers and having too few would make what you see happen more frequently. You can enable `case` for the range to have any number of bullets (and other case-aligned glyphs) align.

**Comment by rsms** [comment]
Here's the OT code
https://github.com/rsms/inter/blob/028839879e33941cbe6018fdc2006980da9e9766/src/features/calt.fea#L298-L325

**Comment by pke** [comment]
> This intended behavior, or rather an intentional compromise. 

Why do other fonts don't have this problem? I tried with Roboto and it worked flawlessly.

> You can enable `case` for the range to have any number of bullets (and other case-aligned glyphs) align.

How does one enable `case`? In the font features?

**Comment by Brian-Holland** [comment]
If anyone is looking to disable the case alternative to align the characters in the original issue, you can add this to your CSS:
`font-feature-settings: 'calt' 0;`
