### ISSUE TITLE
Uppercase I with ss02 has slighlty incoherent height on Firefox

### ISSUE THREAD

**Issue by Pierre-Do** [rsms/inter#387]
**Describe the bug**
With a modern version of Firefox (89.0 on Linux Mint) we're seeing slightly incoherent height for the capital I with `ss02` enabled, depending on the font size and weight.

![image](https://user-images.githubusercontent.com/1904504/122673865-ddd51a00-d1d2-11eb-94c4-f8109b53035e.png)

(using the Lab: https://rsms.me/inter/lab/?feat-ss02=1&letterSpacing=-0.1&lineHeight=0&size=29&weight=500)

Our production website:

![image](https://user-images.githubusercontent.com/1904504/122673892-fe9d6f80-d1d2-11eb-9594-f8c53f88297f.png)

(ref: https://www.qoqa.ch/fr)

This issue isn't seen on Chrome Desktop for instance.

**To Reproduce**
1. Open the sandbox with Firefox 89
2. Set the font-weight to 500
3. Enable `ss02`
3. Increase the font-size until the issue is visible

**Expected behavior**
The height of the `I` glyph should be consistent across modern browsers and font-sizes with `ss02` enabled

**Screenshots**
See description

**Environment**
- OS: Linux Mint 20.1
- Firefox 89
- Version 3.18 (and I assume 3.19 if the Lab is running this version)

**Comment by Pierre-Do** [comment]
Same behaviour with `cv08`.

**Comment by VladWinner** [comment]
This also happens in Chromium-based browsers on Android 10-11, at least since Inter v3.15.

**Comment by rsms** [comment]
That's wild. This does not repro in other font renderers for me so it must be something specific to the font renderer and its specific configuration you are using. Could you see if your OS has font hinting enabled? (aka "ClearType" and sometimes incorrectly labeled "sub-pixel antialiasing")

Here's what it looks like in Firefox on macOS: (correct and as expected)
<img width="905" alt="Screen Shot 2021-06-25 at 15 01 33" src="https://user-images.githubusercontent.com/47046/123489183-4bfc5100-d5c6-11eb-851e-43426cb30a9b.png">

**Comment by rsms** [comment]
Looking at the font's glyph data, the "I.1" glyph looks correct:
<img width="2223" alt="Screen Shot 2021-06-25 at 15 05 44" src="https://user-images.githubusercontent.com/47046/123489498-f7a5a100-d5c6-11eb-96c0-02b44e573387.png">

My best guess is that this is an issue with TrueType hints. However, the lab page does not use fonts with TrueType hints, so that leaves your OS and/or Firefox. It may apply just-in-time auto-hinting and then use those guesstimated hinting programs to inform something like FreeType's ClearType-inspired hinter (which isn't great.) That would explain why the top bar of the "I" is raised sometimes and lowered other times.

**Comment by rsms** [comment]
@VladWinner Interestingly the font you are comparing Inter with in the second screenshot also has a incorrectly-rendered "I". I suspect this is an issue with the font renderer indeed as I can't repro this with either Chrome, Safari, Firefox on Mac, Sketch, Figma or anything else I've tried (that covers the following font renders: Apple ATS, FreeType, Harfbuzz, Adobe.) I really have no idea how to debug this and it might not even be related to Inter (since a similar issue is present in a different font.) Maybe worth filing an issue with the Android and Mozilla teams.

**Comment by VladWinner** [comment]
> However, the lab page does not use fonts with TrueType hints, so that leaves your OS and/or Firefox.

I also can't repro this with latest Firefox (Windows 10) or any other browser in Windows 10:
![image](https://user-images.githubusercontent.com/13555921/123493046-f9518200-d623-11eb-80a0-e3f373061ec8.png)

So most likely this problem occurs only with Android and Linux font renderer:
![image](https://user-images.githubusercontent.com/13555921/123493565-7af5df80-d625-11eb-8c06-037a33c6c85a.png)

**Comment by Pierre-Do** [comment]
> So most likely this problem occurs only with Android and Linux font renderer

I concur, I haven't been able to reproduce it on Windows or macOS (using Browserstack) and I do not see the issue either on Chrome or Opera on my GNU/Linux system.

I've also played a bit with Firefox font settings without being able to pinpoint the culprit. It does seem to be some Firefox weirdness as pointed out by @rsms (thanks for the replies and investigation BTW mate!).

**Comment by cscheffauer** [comment]
+1
