### ISSUE TITLE
unable to type hexadecimal strings with 0x prefix

### ISSUE THREAD

**Issue by figma-joey** [rsms/inter#404]
**Describe the bug**

**To Reproduce**
1. Type any hex with starts with digit, such as 0x10 with Inter (figjam default)
2. See 0 and multiplication sign instead of 0x

**Expected behavior**
Expect hex numbers to stay hex numbers. If you are measuring something, 0 x something is not very common.

**Screenshots**
![image](https://user-images.githubusercontent.com/39931796/135315911-b2e9ba7b-1fca-41d1-a516-76f788643217.png)

**Environment**
- OS: MacOS 10.15.7
- Firefox 92.0.1
- Inter on Google Fonts and in Figjam

**Comment by rsms** [comment]
(timeout)

**Comment by danc86** [comment]
What does "(timeout)" mean? It seems like this is still an issue. I recently tried switching to Inter for my UI font on my Linux desktop, and it works great for that purpose (thanks for your hard work in making such a legible font!) but because I'm a programmer I see hex numbers in a lot of places, like in my bug tracker and wiki pages.

It would be great if Inter could display 0x prefixed numbers properly without having to turn off all contextual alternates for my entire desktop (not actually sure how I can even do that...)

**Comment by rsms** [comment]
Here's what it looks like in version 4:

<img width="1711" alt="Screen Shot 2023-04-19 at 09 49 25" src="https://user-images.githubusercontent.com/47046/233146819-335e091d-9f8f-4c0b-8d93-c1503c313cde.png">
