### ISSUE TITLE
Add U+2304 DOWN ARROWHEAD

### ISSUE THREAD

**Issue by azapletal** [rsms/inter#414]
I see UP ARROWHEAD (U+2303) but I miss the down variant (or do I oversee something?)
The latter might be useful for dropdown menu constructions and the like.

**Comment by rsms** [comment]
(I'm assuming you are asking for U2304 "DOWN ARROWHEAD")

It's not in Inter as I haven't seen it used and can't think of a scenario where it would be useful to have it as a glyph in Inter.

U2303 is used for the keyboard control symbol (it is this way because early ANSI keyboards applied XOR to the regular characters when ctrl was pressed, thus the circumflex-like "xor" symbol :-)

**Comment by azapletal** [comment]
Thx for your reply :)
Well, I completely agree with you when we talk about dedicated UI elements like icon-decorated buttons, user menus etc..
But if you have some sort of inline / text-only situation you might want to have a less obtrusive solution. 
Just think of a typical restyling of the HTML `<select>` via pseudo-element ::after. Putting a DOWN ARROWHEAD into "content" does the job. 
If I had a choice I'd always prefer to use a character from my native font.

**Comment by rsms** [comment]
Added in https://github.com/rsms/inter/commit/4b01ef87833d5f3810e16e6b08941ae8dbd4ab5a

![einarst8u](https://github.com/rsms/inter/assets/47046/c5492a0e-65ee-4685-9459-88961ba80b6a)
