### ISSUE TITLE
Add old style figures (numbers) and Shavian alphabet glyphs

### ISSUE THREAD

**Issue by Shavian-info** [rsms/inter#422]
I have developed a set of glyphs for old style figures (numbers), including stylistic alternatives and tabular spaced versions:

<img width="550" alt="Screen Shot 2022-01-18 at 3 34 42 pm" src="https://user-images.githubusercontent.com/59408625/149871990-7498e58b-16fd-453c-b838-370ee43fb743.png">

I have also developed a set of [Shavian alphabet](https://en.wikipedia.org/wiki/Shavian_alphabet) glyphs (U+10450..U+1047F) following the proportions and design philosophy underpinning Inter:

<img width="1291" alt="Screen Shot 2022-01-18 at 4 29 54 pm" src="https://user-images.githubusercontent.com/59408625/149876496-35a38107-c5a2-4c18-a9ae-4e000fb424af.png">

The source files (.glyphs file and edited Interactive Lab index.html to include the 'onum' feature) are at [https://github.com/Shavian-info/inter](url).

I would be happy to contribute these if there is interest, but thought I should ask before submitting a pull request.

**Comment by ThomasRettig** [comment]
I like it! However, I'm not very sure about the old-style numbers. It looks a lot like Segoe (which is a humanist sans), and does not really have to "geometric-ness" of Inter...

**Comment by Shavian-info** [comment]
Thanks for the positive feedback. Re the old-style figures, I'm guessing that you're referring to the terminals on the 3, 5, 6 and 9? I see what you mean - I tried using the same terminals as in the lining figures but wasn't convinced by the result. The rest of the old-style figures are basically the original Inter figures made a little narrower to ensure that the short 0, 1 and 2 don't look out of proportion.

**Comment by rsms** [comment]
This is really impressive!
And I'd like to say that I really appreciate that you opened this issue asking/talking rather than just submitting a PR. Thank you :-)

I agree with @ThomasRettig that the old-style figures feel like they don't quite belong (for example, the slightly tapered bottom stem of "3") It is very rare for a grotesk (esp a geometric one) to have old-style figures. Looking around at some other fonts in this category, the only family I found with support is Whyte. Old-style figures are mostly a stylistic option (and Inter is not open to stylistic changes anymore.) This article does a good job of explaining a bit about it https://www.fonts.com/content/learning/fontology/level-3/numbers/oldstyle-figures

Rather than merging, I think it would be better if your "Shavian Inter" project continued as a free-standing project. It will make it possible for you to continue improving it (and make your own decisions like including old-style figures.) The Glyphs format maker diff & merge a very costly operation (I have to spend a ton of time manually going through the actual file changes) making merging a rare thing.

**Comment by rsms** [comment]
I've added a link to your project in the main project readme: [https://github.com/rsms/inter#derivative-versions](https://github.com/rsms/inter#derivative-versions)

**Comment by rsms** [comment]
Feel free to close this issue if you agree with the above :-)

**Comment by Shavian-info** [comment]
Thanks @rsms. Understood. This seems like a good way forward. 

One question before I close the issue: if I am creating a separate project, it would make sense to have a different name for the font to avoid confusion. I was thinking 'Inter Alia' to give credit to your work, but also be distinctive. Would you have any objections to this?

**Comment by Derpitron** [comment]
WIll the Shavian alphabet glyphs be merged with rsms's Inter, or will they remain separate from the main project?

**Comment by Shavian-info** [comment]
@Derpitron The Shavian glyphs and old style figures will be in a separate project and not merged.

**Comment by Shavian-info** [comment]
I'll proceed on the basis that my proposed name change for my Inter derivative, 'Inter Alia', is sufficiently distinctive. If there are any concerns at all, just let me know.
