### ISSUE TITLE
Add music note symbols?

### ISSUE THREAD

**Issue by watatomo** [rsms/inter#425]
Inter is my favorite font to use in projects. There's just one thing missing from it, for me, which is the eight note symbol `♪`. A lot of the work I do often use that, so it would be really nice if you could include it.

**Comment by jmsoms** [comment]
Re musical symbols, I would find it really helpful if Inter also included the flat sign (♭, U+266D) and sharp sign (♯, U+266F). This way it would be possible to write notes and chords, e.g. B♭, C♯, F♯m7♭5, etc. There are some common internet shortcuts (e.g. using '#' instead of sharp and 'b' instead of flat), but the proper symbols are much clearer.

Sorry if this is the wrong place/way to request this!

**Comment by jakemumu** [comment]
Would love to bump this -- love inter but can't use it due to this constraint

**Comment by rsms** [comment]
Implemented in https://github.com/rsms/inter/commit/94a95d49bb1c23a261eb80f9cc61f2b7b00a94c2, released with version 4.1

<img width="1287" alt="386751718-43e74deb-3401-4f56-a1b6-02dab7b063ac" src="https://github.com/user-attachments/assets/e9c29621-ed96-4aad-bcd0-0131a07d6cd1">

<img width="1184" alt="386756337-5af5a1f4-f87f-480d-b0c5-8cbc4247283f" src="https://github.com/user-attachments/assets/a69e1115-b28e-4d9d-9a0f-782c4b25e201">

**Comment by jakepenn** [comment]
Huge news! Thanks so much -- were sharps and flat symbols included as well?
