### ISSUE TITLE
Weird/bad text spacing on Chrome on Linux

### ISSUE THREAD

**Issue by sunshowers** [rsms/inter#467]
**Describe the bug**
Hi there -- thanks for Inter! I'm looking to replace the font on one of my sites with it.

I'm seeing weird, somewhat ugly font spacing with Chrome on Linux. I see it both on the Inter home page and on the site I'm trying to make changes to.

Firefox on Linux looks great though and if Chrome looked like that I'd switch over in an instant.

**To Reproduce**
1. Open https://rsms.me/inter/ in Chrome on Linux.

**Expected behavior**
Text spacing looks perfect like on Firefox.
* In particular, "ull" in "carefully" isn't smushed together.
* "ili" in failing isn't smushed together.
* Smaller space after "t" and "f".
* "Up" in "Up" isn't smushed together.

**Screenshots**
Chrome:
![image](https://user-images.githubusercontent.com/180618/173962350-e09217d2-2fc9-4303-8afa-5a7fc789bce3.png)

Firefox:
![image](https://user-images.githubusercontent.com/180618/173962377-0a01274e-3836-4e20-8c97-ab7773ebe6f9.png)

On the site I'm trying to make changes to -- this is with font-feature-settings ss01, ss03, cv08, and letter-spacing -0.017em:

Chrome:
![image](https://user-images.githubusercontent.com/180618/173962517-45242084-d46a-4d1d-8582-b9eb089e5779.png)

Firefox:
![image](https://user-images.githubusercontent.com/180618/173962489-ce91531a-ae45-4704-a99d-da7cb4478c4c.png)

**Environment**
- OS: Pop_OS! Linux 22.04 (Ubuntu derivative)
- App that renders the font: Chrome 102.0.5005.115
- Version of font: Inter Regular 3.19 downloaded from https://rsms.me/inter/.

**Comment by sunshowers** [comment]
Another sample from your homepage:

Chrome:
![image](https://user-images.githubusercontent.com/180618/173963148-c51dac45-1a20-4d79-8a30-5ddaf5975931.png)

Firefox:
![image](https://user-images.githubusercontent.com/180618/173963223-ba9ce845-e695-486c-b754-9ef1167cb5dc.png)

**Comment by sunshowers** [comment]
Just built Inter off of master, looks significantly better in Chrome though still not as good as Firefox.

![image](https://user-images.githubusercontent.com/180618/173964061-f37e58a1-96a1-41d7-aed6-1344638f880d.png)

**Comment by sunshowers** [comment]
A bunch of discussion happened on twitter: https://twitter.com/sunshowers6/status/1537220771138785286 -- it seems like some sort of weird Linux fontconfig thing might be the culprit, but since Inter off of master looks significantly better than the release version there might be things you could do. Thanks again!

**Comment by sunshowers** [comment]
Ah, sadly it's actually the fact that I switched to hinted fonts that made the difference. The non-hinted fonts off of master look the same as the release fonts.

**Comment by sunshowers** [comment]
Unfortunately it looks like the issue is with the Chromium flatpak. The snap version looks fine. There might be nothing else to do here.

![image](https://user-images.githubusercontent.com/180618/174243972-de370014-a4b8-40c4-94e6-49e6a36c0464.png)

**Comment by rsms** [comment]
That looks truly horrible. My suspicion is that Chrome delegates text rendering to the OS and many Linux distros uses Freetype which is not very good at shaping, especially when distros decide to enable hinting, which is usually a bad idea. AFAIK Firefox does its own font rendering (using Harfbuzz I think) which is why it looks good there.

I would contact your Linux distribution maintainers to see if they can use higher-quality text rendering. You can test in Figma, which doesn't depend on the OS at all and uses Freetype & Harfbuzz to do layout, shaping etc. It can serve as a "this is how good it can look if you configure it well."

I'm going to close this as it's not an issue with Inter, but rather some software (with rounding bugs, which is why you get wonky spacing; UPM 2048 is a power-of-two so bad arithmetic code is less likely to be found with that scale.)
