### ISSUE TITLE
[Inter Variable 3.19] Some glyphs bug out when using slant feature

### ISSUE THREAD

**Issue by MattMayuga** [rsms/inter#481]
**Describe the bug**
When using the slnt (slant) feature in Inter Variable, some glyphs such as the reversed exclamation mark and double dagger become messed up.

**To Reproduce**
1. Open fontgauntlet.com
2. Open Inter Variable by dragging and dropping it into the site
3. Click on Glyph Sets and then Entire Font
4. Use the slant feature

**Expected behavior**
All glyphs should be slanted without issues.

**Screenshots**
Before
![image](https://user-images.githubusercontent.com/26103475/188162134-fb1f6c9c-ed3f-4760-83f8-b91c8379024a.png)
After
![image](https://user-images.githubusercontent.com/26103475/188162380-ca855657-1e5a-4457-b69a-8ab4b6a7e8ca.png)

**Environment**
- OS: Windows 10 Pro Education 64-bit, version 21H2
- Browser: Waterfox G4.1.4 (based on Firefox)
- Version of font: Inter. Version 3.019;git-0a5106e0b

**Comment by kenmcd** [comment]
I can see the issue with the reversed exclamation mark, but the double dagger looks OK.

The reversed exclamation mark has a different start point on the lower element in the 3 regular masters vs. the italic masters.
So if you set the slant to some intermediate setting you see the distorted element.

This appears to have been fixed in the current beta so I do not think the font developer is going to go back and fix this in v3.19.
You can get the latest beta build here: https://github.com/rsms/inter/discussions/463
