### ISSUE TITLE
Glyphs using a single shape overlapping itself failed to be flattened

### ISSUE THREAD

**Issue by newforms** [rsms/inter#51]
![dulcmmrvwaava-8](https://user-images.githubusercontent.com/35104/35284030-6520c9ac-001f-11e8-8182-3434ff35d782.jpg)

Overlaps aren't removed in glyphs using a single shape, overlapping itself (i.e. "P", "e", "6", "9", etc.).

**Comment by rsms** [comment]
The bug is in fontbuild at https://github.com/rsms/inter/blob/f7868ac6205e9d3388059179a472365835a8fd9b/misc/pylib/fontbuild/Build.pyx#L307

An optimization looks at a glyph's contours and if there's only a single contour—as the case with e.g. "e"—it skips the expensive union boolean operation. There's probably a cheap way to check if there's any overlap even for single-contour glyphs.

**Comment by rsms** [comment]
I have a fix for this, but it increases build times by a considerable amount of time (29s -> 43s). Before pushing a fix for this, I want to investigate if I can speed up the process.

**Comment by rsms** [comment]
I wasn't able to find a way to speed things up, so considering 57238c6c829bd35b5632d414b44d503124d94d49 to fix this.

**Comment by rsms** [comment]
Here's a build with the fix
[Inter-UI-2.5-57238c6c82.zip](https://github.com/rsms/inter/files/1661270/Inter-UI-2.5-57238c6c82.zip)

**Comment by rsms** [comment]
Beta release with these changes incorporated: https://github.com/rsms/inter/releases/tag/v2.5-beta

**Comment by newforms** [comment]
Thank you!
