### ISSUE TITLE
V4: Inter Display is preferred by fontconfig instead of Regular (Linux)

### ISSUE THREAD

**Issue by barmadrid** [rsms/inter#515]
**Describe the bug**
In Linux, V4 Beta 7 of the font, Inter Display is preferred by fontconfig instead of Regular (Linux)

**To Reproduce**
1. Install fonts
2. Run: fc-match "inter" 
3. Inter-Display.otf: "Inter Display" "Regular" is the output.

**Screenshots**
![Screenshot from 2022-10-27 18-52-24](https://user-images.githubusercontent.com/61072940/198413096-19c4205e-832e-4a93-a61f-60623c239ca6.png)

**Environment**
- OS: Arch Linux 6.0.2.arch1-1
- fontconfig version 2:2.14.1-2
-  Gnome shell 43

**Comment by apcamargo** [comment]
I have the same problem with Inkscape and Microsoft Office

**Comment by kepstin** [comment]
It looks like the problem is that the Inter-Display.otf actually has two family names set:
```
$ fc-query /usr/share/fonts/inter/Inter-Display.otf 
Pattern has 26 elts (size 32)
	family: "Inter Display"(s) "Inter"(s)
	familylang: "en"(s) "en"(s)
	style: "Regular"(s) "Display"(s)
	stylelang: "en"(s) "en"(s)
	fullname: "Inter Display"(s)
	fullnamelang: "en"(s)
	slant: 0(i)(s)
	weight: 80(f)(s)
	width: 100(f)(s)
	foundry: "RSMS"(s)
	file: "/usr/share/fonts/inter/Inter-Display.otf"(s)
```

I took a look in fontforge to see what was going on, and it looks like the issue is that the TTF Family is set to "Inter Display", but the PS Family Name is set to "Inter" . fontconfig seems to read both fields, and in the case of conflicts it makes the font be aliased under both names.

**Comment by thunderbird-1990** [comment]
I use Inter as a my system font (Arch Linux + KDE).

This is actually a relatively serious issue, because it means that the latest versions of Inter Display practically disable Inter and change how the system interface looks.

I can confirm that Inter Display beta 2 (Inter-3.19-display-beta-2) doesn't have this issue. I currently have that version installed.

Thanks.

**Comment by rsms** [comment]
@kepstin I think this comes from a workaround for this bug: https://github.com/googlefonts/glyphsLib/issues/820 — we set openTypeNameWWSFamilyName manually to "Inter Display". I think fc-query lists both the `familyName` and `openTypeNameWWSFamilyName` entries.

**Comment by rsms** [comment]
I think this is related to #519 which has a fix out. Please try this build:

[Inter-4.0-e12027c4c1.zip](https://github.com/rsms/inter/files/11593291/Inter-4.0-e12027c4c1.zip)

**Comment by barmadrid** [comment]
Seems to be working now based on https://d.rsms.me/tmp/Inter-4.0-bd33b4148b.zip

**Comment by apcamargo** [comment]
I tried [d.rsms.me/tmp/Inter-4.0-bd33b4148b.zip](https://d.rsms.me/tmp/Inter-4.0-bd33b4148b.zip) in Microsoft Word and the problem seems to persist. The Display variant is chosen when I pick "Inter" in the font menu.

**Comment by apcamargo** [comment]
Moving Display to a separate family seems to have fixed the issue for me too

**Comment by rsms** [comment]
@barmadrid @apcamargo thank you for confirming!

**Comment by apcamargo** [comment]
Thanks, @rsms!
