### ISSUE TITLE
ɑ and ɒ are not rotation-symmetric with each other

### ISSUE THREAD

**Issue by JapanYoshi** [rsms/inter#529]
> Did you get the font from Google Fonts? Then please head over to
> https://github.com/google/fonts/issues
> and file an issue with Google Fonts.
> If not, REMOVE THIS PARAGRAPH BEFORE FILING YOUR ISSUE.

**Describe the bug**

ɑ and ɒ are both characters used in the International Phonetic Alphabet. Despite the name "alpha", the Latin lowercase alpha is intended to be a "single-storey" lowercase a, and the 180° rotated version of ɒ (Latin lowercase turned alpha).

**To Reproduce**
1. type ɑ and ɒ
2. compare their shapes

**Expected behavior**

They should be rotated versions of each other.

**Screenshots**

![image](https://user-images.githubusercontent.com/8707990/215323529-438b6f36-5623-4cea-9f55-59f0750de559.png)

**Environment**
- OS: [e.g. macOS 10.14] Windows 10
- App that renders the font [if applicable; e.g. Chrome, Adobe Illustrator] FontForge, Inkscape
- Version of font [e.g. "Inter Regular 3.0;8cf05e4a" — you can use fontdrop.info to find out the version] Inter Thin 3.019; git-0a5106e0b

**Additional context**

Segoe UI:
![image](https://user-images.githubusercontent.com/8707990/215323695-33adc5a2-eeb7-4a1c-a015-ae192777166d.png)

DejaVu Serif:
![image](https://user-images.githubusercontent.com/8707990/215323737-24d0586d-2864-44c1-9df3-79b1ee2cf7fa.png)

**Comment by shigeno2** [comment]
Note: This problem seems to occur regardless of whether the download source is Google Fonts or GitHub. I have tried three versions: v3.019 from Google Fonts, v3.19 and v4.0-beta7 from GitHub.

Essentially the same issue was briefly mentioned in the middle of the thread #32, although it’s not the main topic there:
> BTW Latin alpha (ɑ) should be redesigned as what you made for small a + `cv11` feature, see the official Unicode chart for IPA Extension.

The letters involved in this issue, in some fonts that support these letters:
<img width="500" alt="2023-03-16_103933" src="https://user-images.githubusercontent.com/105553172/225533704-cf35cc81-642e-4329-8e67-2788b05f535f.png">
Also in the official Unicode chart (https://unicode.org/charts/PDF/U0250.pdf) and in the IPA charts with four different fonts (https://www.internationalphoneticassociation.org/IPAcharts/IPA_chart_orig/IPA_charts_E.html), the LATIN SMALL LETTER ALPHA glyphs look like single-storey “a” rather than Greek alpha. The glyph shapes in these charts are not prescriptive, but should be taken into account, IMHO.

**Comment by moyogo** [comment]
@JapanYoshi 
> > U+0251 ɑ is used for both script-a and latin-alpha

> That’s like saying U+03B2 is used for both German eszett and Greek beta. U+0251 is an IPA symbol shaped like a single-storey 〈a〉, and U+03B1 is the Greek character alpha. Script 〈a〉 is U+1D4B6, by the way.

Let me emphasize it: LATIN-alpha. See the character notes in the Unicode charts, notice the Unicode 1.0 name "latin small letter script a". Script-a and single-storey a are synonyms in this context. U+1D4B6 is a math symbol and is not relevant.
<img width="501" alt="Screenshot 2023-03-17 at 09 24 33" src="https://user-images.githubusercontent.com/1923747/225851755-40453f4a-4e81-46f6-bbaf-ba70cf96e75d.png">

**Comment by moyogo** [comment]
@JapanYoshi whether we agree or not on if LATIN SMALL LETTER ALPHA is a latin-alpha or not is not relevant to the issue, the current Inter U+0251 is designed in an unusual or dated way for IPA. I’m pointing out other systems than IPA also use the character. The hybrid form adequate for the various systems using the character could be the same or similar to U+0252 turned back rather than U+0061 with cv11 applied, which is inadequate for systems using the latin-alpha shape or those using U+0251 and U+AB64 contrastively.

**Comment by rsms** [comment]
U+0251 and U+0252 after f5810aebd8f8460c6cc7d0a4220f2345383c58e3:
<img width="1046" alt="Screen Shot 2023-04-04 at 12 21 38" src="https://user-images.githubusercontent.com/47046/229899136-e7d519d0-d858-4f6a-815a-b3f71d8eccea.png">

**Comment by rsms** [comment]
Included in https://github.com/rsms/inter/releases/tag/v4.0-beta8
