### ISSUE TITLE
Bullets jump when typing numbers into password input on Android

### ISSUE THREAD

**Issue by nazar1ua** [rsms/inter#533]
Reproduction: https://nazar1ua.github.io/inter-bug-reproduction/

Android 8.1.0, Chrome

**Comment by kenmcd** [comment]
It appears Contextual Alternates (`calt`) is being applied to the text input.
Notice it only moves the previous five bullets.
Only happens when "Make passwords visible" is enabled.
So when the character input appears for a moment, the contextual alternates is applied, and then when the input character disappears `calt` no longer applies and the five bullets drop down.

If you can disable `calt` on the input field that would solve it.
Assume you are using v3.19.
Just checked v4 beta 7 and it is the same.
Not sure that this is a font problem.

**Comment by nazar1ua** [comment]
Thank you very much! I think this must be documented

**Comment by rsms** [comment]
Seems like a bug in chrome — the case alternates should only activate when adjacent to an upper-case character
