### ISSUE TITLE
Multiple asterisks leading to an uppercase letter

### ISSUE THREAD

**Issue by yishn** [rsms/inter#57]
I really like how the asterisk aligns itself with uppercase letters, but take, for example

~~~
**ABBA**
~~~

you'll see that the last two asterisks are aligning themselves to the last A, whereas the very first asterisk does not align with the first A like the second asterisk does.

In Markdown it's common to enclose words in two asterisks, but if the word starts with an uppercase letter and ends with a lowercase one, for example

~~~
**Inter**
~~~

the second asterisk looks very out of place. Is there a way to disable this auto alignment?

**Comment by rsms** [comment]
reference
<img width="148" alt="screen shot 2018-03-19 at 09 17 15" src="https://user-images.githubusercontent.com/47046/37607863-57033230-2b56-11e8-80fa-b775d48767dc.png">

**Comment by rsms** [comment]
You can disable contextual alternates (how depends on the platform and app you're using)
Better solution might be to make sure that `**M` yields `<capital asterix><capital asterix>M` rather than `<default asterix><capital asterix>M`

**Comment by rsms** [comment]
Since left-side matching doesn't cascade automatically with contextual alternates, each left-hand side match needs to be explicitly matched and replaced. It's a balance between code complexity, layout performance and number of glyphs matched. I choose to match up to five glyphs on the left side, as demonstrated in this screenshot:

<img width="379" alt="screen shot 2018-08-29 at 10 41 06" src="https://user-images.githubusercontent.com/47046/44805075-174abf80-ab78-11e8-99e4-e65916db2852.png">
