### ISSUE TITLE
More significant (“Curly”) commas

### ISSUE THREAD

**Issue by be5invis** [rsms/inter#570]
It will be interesting if Inter could add curly (“traditional”) commas (as well as semicolons, quotes, and comma marks).

![image](https://github.com/rsms/inter/assets/240091/19f22746-3549-413a-83c1-b04e90498e56)

**Comment by rsms** [comment]
v4 (what's in git) actually does contain "curly" single quotes, which I drew a year ago and really loved, but couldn't use since the rest of Inter doesn't fit it, but I'm considering making these available as a stylistic set. What do you think @be5invis, is a stylistic set the "right thing to do" here?

<img width="922" alt="Screen Shot 2023-05-11 at 14 47 58" src="https://github.com/rsms/inter/assets/47046/68183f2c-d738-44e5-8f95-cb9702208ec9">

I would also consider making these rounded separators the default for Display (opsz=32) with some interpolation tricks to maintain straight ones for the text (opsz=14) styles.

**Comment by TaigaYamada** [comment]
I know I'm not the one asked for opinion, but I want to contribute to the discussion. 

I feel like curly separators as the default for just the display styles may be a bit of departure from the established style.

Differences between text and display sizes up to this point have all been focused on text size and legibility. However, adopting a completely different design for separators would bring a new design styling to the display sizes, not just adjustments for legibility.

To keep display and text styles cohesive & consistent, I think implementation as a stylistic alternative is the best way.

**Comment by rsms** [comment]
> I feel like curly separators as the default for just the display styles may be a bit of departure from the established style.
> 
> Differences between text and display sizes up to this point have all been focused on text size and legibility. However, adopting a completely different design for separators would bring a new design styling to the display sizes, not just adjustments for legibility.

I agree with this. Let's not have the "Display" styles diverge too much from the "text" styles.

So should this be...
1. a stylistic set
2. mapped to ill-fitting-but-assigned Unicode codepoints like U+275C "HEAVY SINGLE COMMA QUOTATION MARK ORNAMENT"
3. only mapped to private Unicode codepoints
4. let's not do this (do nothing)

I'm leaning toward 1 or 4. Thoughts?

**Comment by TaigaYamada** [comment]
+1 for 1!

**Comment by be5invis** [comment]
Assigning it into a SS will be ideal.

**Comment by rsms** [comment]
438af9f29b607b8717bda892a4fa2e36cea56057 introduces "round" quotes and commas under `ss03` — please try it out and let me know how it feels:

[Inter-4.00-438af9f29b.zip](https://github.com/rsms/inter/files/11580575/Inter-4.00-438af9f29b.zip)

![roundqc](https://github.com/rsms/inter/assets/47046/e9e23bf7-6bee-48a4-b679-3a176fef8947)
