### ISSUE TITLE
Request: tabular `1` without buttom slab

### ISSUE THREAD

**Issue by pkj-l** [rsms/inter#579]
Hope to restore tabular figure `1` without buttom slab, like old versions of Inter, by adding a character variant (cvXX).
Thanks!

**Comment by AchillesBoi** [comment]
Is this happening? The tabular `1` without the bottom slab looked so much better than the new one. I would also like to have the old version back as default, and the new one available only as a variant.

**Comment by breispeloton** [comment]
Hello!  I’m an Android engineer at Peloton and we’ve recently been using one of the earlier beta releases in some of our different client platforms.  Upgrading to the stable release version is a bit of a blocker for us since our design team feels very strongly about having a “no bottom slab” variant for tabular numbers.

We’re happy to take on the work to contribute to this change (I read the CONTRIBUTING.MD!), but we wouldn’t want to put the time in if you think this is a non-starter.
Could you please confirm that adding this character variant for tabular 1's would be likely  accepted?  If so, I’d be happy to talk about what the next steps are and how we can work to add this functionality.  Thanks for your time and consideration!

**Comment by rsms** [comment]
This has been implemented in https://github.com/rsms/inter/commit/a264bbe519c229b6ac149b625d8b5f5ba6ea41aa and will be included in the next release (version 4.2), accessible via cv15.

<img width="1304" alt="Screen Shot 2024-11-18 at 18 17 06" src="https://github.com/user-attachments/assets/8aef7457-bd66-46fc-95c6-b50da5e26453">

**Comment by bibixx** [comment]
Hey, do you have any docs/plans with the release schedule? Waiting for this one so much 🤞🏻
