### ISSUE TITLE
InDesign alternate style set 'a' not functioning 

### ISSUE THREAD

**Issue by dpor** [rsms/inter#605]
**Describe the bug**
In Indesign I can not load the stylist set that swaps the open 'a' to the closed 'a'.
Apparently it should be stylist set 11 but none of the un-named sets work in Indesign. 
Only the first 4 named sets seem to load correctly within Indesign.

**To Reproduce**
Steps to reproduce the behaviour:
1. Type a normal 'a' within text box in InDesign using Inter Medium or any Inter weight.
2. Try to change the Open Type stylist set so that the 'a' changes to the closed 'a' automatically. 
3. One of the sets should change the 'a' but I can not get any of the un-named style sets to work within Indesign.

**Expected behaviour**
One of the stylist sets should universally change out all lowercase 'a' characters to closed 'a' character so that the style can be set for the whole document.

**Screenshots**
<img width="809" alt="image" src="https://github.com/rsms/inter/assets/3615115/2c223bbe-de56-4504-ae2d-fbb39e7a866c">

<img width="960" alt="image" src="https://github.com/rsms/inter/assets/3615115/88b71e96-f45c-4888-9f63-a34ca4555511">

**Environment**
- MacOS: 13.5
- Adobe Indesign 18.5
- Version of font: Inter Medium 3.019;git-0a5106e0b

**Comment by kenmcd** [comment]
Inter v3.19 only has four stylistic sets (ss01-ss04) - which is what is listed in your image above.
_Single-story a_ is character variant 11 (cv11), not a stylistic set.

**Comment by acordy** [comment]
Hi, chiming in as this relates to a question from @dpor I was trying to help with earlier [https://github.com/rsms/inter/discussions/604](https://github.com/rsms/inter/discussions/604).

@kenmcd is right: it does look like Inter supports only the four stylistic sets, and that there is a distinction between _stylistic sets_ and _character variants_. So @dpor, part of what I said earlier doesn't apply, and controlling the alternate character wouldn't be exposed through that menu. This isn't an issue with Inter.

Looking around quickly, it doesn't appear that this is exposed in a convenient way in the Character pane in InDesign. If that's the case (again, I only looked at this quickly just now), then that's a shame, but still an InDesign issue.

You can still probably freeze the character variant as I suggested in the discussion linked above, or go the script method. After having looked at this quickly now, it also looks like you can manually control this through the Glyphs pane, or by doing a find and replace on the document. Again not ideal, but hopefully these can provide you a workaround. If you just always want to use the alternate, I'd probably go the feature freeze route and then use those fonts and not think about it again.

In any case, it's not an Inter issue, so I think it's safe for you to close this issue, since there's nothing to be fixed on this end.

**Comment by dpor** [comment]
ah great - thanks for the input @kenmcd and @acordy 
Much appreciated.

I'll check out the other Indesign work-arounds and see if they can work in this situation.
We have to use the font in a shared template style/working file so was really looking for a universal paragraph style option so the 'a' automatically swaps when using that set paragraph style for multiple users across multiple desktops.

But is it not strange for font files to have character variants that you can not universally access with Adobe style settings?
Seems odd that you can only access that 'a' manually (or find replace) to swap out? No?
Is there a way to propose this as an update to the font or is that ridiculous? 
Excuse my ignorance of this platform or processes - I've not really used GitHUb before so don't really know the best way to find work arounds to the problem.

**Comment by acordy** [comment]
Hey, my comments on this @dpor:

> I'll check out the other Indesign work-arounds and see if they can work in this situation.

If you like I'm happy to try and find a solution that works for you, I use InDesign often as well and might just need one too down the line! But let's continue this discussion in your original question post since I don't think it's relevant here.

> But is it not strange for font files to have character variants that you can not universally access with Adobe style settings?

I would call it more of a shame than strange, since there's precedent for Adobe and InDesign in particular lacking or partially implementing OpenType features (I've dealt with other well-documented issues they had/have with variable fonts).

You mentioned it works in Figma, which I tested and it does, but that's because they've implemented it. If you look at the menu in Figma under _Details_ in _Type Settings_, you'll see two sections, one for _Stylistic sets_ and one for _Character variants_.

> Is there a way to propose this as an update to the font or is that ridiculous?

Inter is using the features correctly. Stylistic sets are modifiers to _sets_ of characters, for instance `ss02` "Disambiguation" swaps out a whole set of glyphs for ones that resolve ambiguities. Character variants swap out just one set of glyphs, like in your case the "a" and its accented versions for the single-storey "a" with `cv11`.

I don't think it's fair or makes sense to request that what should be a character variant be implemented as a stylistic set, just because InDesign only exposes a UI for handling stylistic sets. If there's anything to propose it's for Adobe to include Character Variants in InDesign's UI.

Like I said above, happy to continue looking for a solution that works for you in your original Q&A post, we can continue discussing there.

**Comment by dpor** [comment]
OK - I'll try and flag this with Adobe and see what they say.
I still don't fully understand all the technical bits and pieces. 
Like it seems much easier to update the font with a new stylistic set (similar to the style that just swaps out the 'r') than to approach Adobe to update their app. 
But again, I don't know much about all the behind the scenes technical bits so I'm happy to close this issue.
