### ISSUE TITLE
CDN does not provide some features

### ISSUE THREAD

**Issue by jonhue** [rsms/inter#62]
When importing `https://rsms.me/inter/inter-ui.css` in my CSS I am missing some features:

* Medium weight
* Contextual alternates

When using the browsers dev tools to switch the font weight between `400` and `500`, there is no visual change.

When turning on `calt`, `->` is not being displayed as an arrow. Trying to explicitly set the Unicode renders this icon: `࢐`.

Do I have to pass specific params to the URL to get these features?

**Comment by rsms** [comment]
Can you please provide some additional information:
- how you're importing that CSS file (if it's a web browser, what browser, browser version, etc)
- operating system
- what do you get from a network logger when loading the CSS? (both Chrome and Firefox has great built-in GUI for inspecting network operations; View > Developer > Developer Tools in Chrome)
- calt is enabled by default in pretty much every app, os and web browser. You should not need to enable it manually (though you can disable it manually if you want.) Again, can you please confirm using web browser developer tools that the text you're looking at is indeed both using Inter UI and that you're not accidentally importing some other CSS that disables contextual alternates?
- no "parameters" needed to the URL of the CSS file — it's just a static file that includes directions for the complete family.

BTW, I'm asking all this since I can't reproduce this and no one else is reporting this. It's very likely an issue on your end, but I'd still like to make sure that's the case. Thank you.

**Comment by jonhue** [comment]
My bad. You caught me with your 4th point. I was setting the font family to `inter-ui`. After changing it to `'Inter UI'` everything works perfectly. Thanks for the great font! 😍
