### ISSUE TITLE
Consider re-publishing .woff files to CDN

### ISSUE THREAD

**Issue by altano** [rsms/inter#631]
Hello,

Firstly, thank you SO MUCH for this wonderful font and all your hard work.

It looks like you deleted the woff and otf files in [this commit](https://github.com/rsms/inter/commit/310a73bad970c7ab593f9da4a1db12333c97f5ea) ~and it looks like requests to the woff files (e.g. https://rsms.me/inter/font-files/Inter-Regular.woff) silently redirect to the woff2 files~.

I know woff is quite old but there are some server-side tools that parse font files (such as [satori](https://github.com/vercel/satori)) that [have no woff2 support planned](https://github.com/vercel/satori/issues/3):

> TTF & OTF are faster to load and parse, so on the server side we will always recommend using them unless there's a size limitation. WOFF is a good balance of size and parsing speed (smaller but slightly longer to load).

Some people such as myself were relying on these files existing and actually being woff files and not woff2. Having it silently change to woff might break things for others.

I will work around this for now by hosting the woff files myself, but others may be hitting this issue as well without even realizing it.

**Comment by rsms** [comment]
Hello!

I'm pretty hesitant to add .woff files back. It really is a deprecated format, inferior to woff2 in every way.

The font files in the `docs/font-files/` directory is for the CDN which is backed by github (as you know) and thus I need to limit the file sizes there to not make this git repository grow out of proportions in size (since over time, all history is saved and these files being non-diffable by git are stored as entire copies in the git history.) Also note that github LFS does not work for these files for complicated reasons (I once tried, took down the website in the process and had to have github customer support help out and restore the repo from a backup as the changes could not be reverted.)

I'm surprised to hear that you are using tools which do not support woff2. If those tools support ttf or otf, you can use those fonts instead. Every release contains ttf and otf files in the `extras` directory.

Another workaround, if you absolutely need woff files, is to convert the ttf files (again, in the `extras` directory) to woff.

For projects like satori, I recommend offering a patch that adds support for woff2. They use opentype.js which doesn't support woff2 because it would make their javascript too large. Instead the opentype.js authors suggest [decompressing the woff2 data before handing it over to opentype.js](https://github.com/opentypejs/opentype.js/tree/6408975ed2c6e91ac8376d8be6290b2f705e1724?tab=readme-ov-file#loading-a-woff2-font). I think you'd want to add code for handling woff2 here somewhere: https://github.com/vercel/satori/blob/main/src/font.ts#L146
