### ISSUE TITLE
v4: min `opsz` == max `opsz`

### ISSUE THREAD

**Issue by rben01** [rsms/inter#635]
**Describe the bug**
I am not even sure this is a bug or not, but in the (new and awesome!) v4, `opsz` 14 (min) appears identical to `opsz` 32 (max). But 14.1 does look like the `opsz` of a tiny font.

**To Reproduce**
1. Set `opsz` to 14 (the min value)
2. It looks just like `opsz` 32 (the max value)

**Expected behavior**
Continuity in `opsz`, so that 14 is just barely different from 14.1.

**Screenshots**

## `opsz` 32
<img width="983" alt="3338CDB9-B802-4F43-AA2F-251E5FA41E28" src="https://github.com/rsms/inter/assets/766670/8a180c32-227c-49da-bf13-633f975c4c10">

## `opsz` 14.whatever
<img width="987" alt="DB031BC1-9F35-4383-832C-7ACE1A63F4AF" src="https://github.com/rsms/inter/assets/766670/a61f55a3-2c49-4170-a8d1-24a41b364788">

## `opsz` 14.0
<img width="999" alt="F6D4FC0F-015F-4A34-BB03-73358280F1A9" src="https://github.com/rsms/inter/assets/766670/4171e924-a1d1-40e0-8685-049a5902b7fb">

**Environment**
- OS: macOS 14.1
- App that renders the font: Safari
- Version of font: 4.0 (https://rsms.me/inter/lab)

**Comment by kenmcd** [comment]
The issue is the Safari browser does not support `opsz` properly.
Try it with Chrome or Firefox.
They both work properly on Windows 10.

**Comment by acordy** [comment]
Setting the CSS property `text-rendering: optimizeLegibility` on either the sample text element or the body (it's inherited) resolves this issue in Safari. Whether it's by design or not, I think I remember reading somewhere that Safari has this property set to `optimizeSpeed` by default in the user agent, and it looks like a consequence is the effect being observed.

In general, I think this is a good property to explicitly set to `optimizeLegibility` on any site, since it hints to the browser and rendering engine to not sacrifice typographic integrity over what I assume is in 2023 a trivial performance hit.

In any case, adding this to the [https://rsms.me/inter](https://rsms.me/inter) site would resolve this issue and possibly avoid confusion for others.

**Comment by rben01** [comment]
On second thought I'm not even sure this is a bug at all — at least, not with either Safari or Inter, but rather, perhaps, with https://rsms.me/inter/lab/. I believe the cause is that setting `opsz` to 14 simply removes the corresponding query parameter from the Inter Lab URL, which, evidently, falls back to the default `opsz` of 32.

**Comment by acordy** [comment]
@kenmcd I don't know if you saw my previous comment, this might be a change to make to the site to resolve the issue on Safari.

@rben01 Without a query parameter in the URL, the optical size is still being set via `font-variation-settings: "wght" 400, "opsz" 14`, so the optical size is explicitly set to 14. You can see this in dev tools. The issue really does appear to be the lack of the `text-rendering` property, which when set to `optimizeLegibility` resolves the issue.

**Comment by alexschcom** [comment]
The initial comment by @rben01, shows the font size is set to 32px, which would cause the font to automatically apply the corresponding optical size. If you change the font size to 14px (and leave the `opsz` param at 14px) you'll see that it actually does work (look at the opened aperture of the lowercase "a", for example). As you scale the font size up, you'll see the optical size adjust with it. To disable this behavior, you can set [`font-optical-sizing`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-optical-sizing) to `none`.

**Comment by rsms** [comment]
Strangely I can't reproduce in Safari.
What you are seeing might be some new behavior in Safari on macOS 14 (which I don't have.) Since opsz is set explicitly 

<img width="1009" alt="Screen Shot 2024-03-22 at 18 33 13" src="https://github.com/rsms/inter/assets/47046/42d56a5c-9e85-4496-85bf-2b5919ddf9f3">
<img width="1009" alt="Screen Shot 2024-03-22 at 18 33 17" src="https://github.com/rsms/inter/assets/47046/5c053112-b8d6-4d3a-be74-d60485cfdefc">
<img width="1009" alt="Screen Shot 2024-03-22 at 18 33 20" src="https://github.com/rsms/inter/assets/47046/a165da6a-3738-4723-9462-5119fe8cbe73">


Same in Chrome, can't repro:

<img width="888" alt="Screen Shot 2024-03-22 at 18 28 50" src="https://github.com/rsms/inter/assets/47046/c6fdb100-a355-4e0e-81dc-d5384299afdb">
<img width="888" alt="Screen Shot 2024-03-22 at 18 29 08" src="https://github.com/rsms/inter/assets/47046/15e38fc4-a4da-46c3-ad64-38375d69820c">
<img width="888" alt="Screen Shot 2024-03-22 at 18 29 12" src="https://github.com/rsms/inter/assets/47046/9bb53cbd-6cfa-4fbc-b3b0-439ef361fe9b">
