### ISSUE TITLE
Missing Open Type Features (Figma)

### ISSUE THREAD

**Issue by augiethehuman** [rsms/inter#683]
**Describe the bug**
Within Figma, I'm unable to access these features"
- ss03 Round quotes & commas
- ss07 Square punctuation
- ss08 Square quotes

**To Reproduce**
Does not show up when using Inter in Figma.

**Expected behavior**
Expected for all Open Type features to be available.

**Comment by kenmcd** [comment]
How would this be an issue with the font?
Ask Figma.

Those are features that are in Inter v4, so they are probably using Inter v3 (which does not have those).

**Comment by augiethehuman** [comment]
Hey @kenmcd,

Firstly, relax a smidge with your response. Secondly, I'm using v4 directly from the website. Not the font that Figma or any other program has internally. It's just a simple question - maybe I'm missing something but a few Open Type features are missing.

Thanks,

**Comment by kenmcd** [comment]
What exact font file/ link are you using?
This: https://rsms.me/inter/font-files/InterVariable.woff2
Is used on the website, and is where the example CSS points.
Just checked that font and the features are working fine.
So are you using another font link?
Or perhaps the issue is with the embedding code.
Or the issue is with Figma?
That font looks fine.

**Comment by rsms** [comment]
It’s an issue with Figma (or you don’t have applicable glyphs in your text selection in Figma, ie user error)
