### ISSUE TITLE
The hyphen/hyphen.case.tf are too overspaced

### ISSUE THREAD

**Issue by cssobral2013** [rsms/inter#740]
**Describe the bug**
The tabular hyphen is so overspaced that, when you, for example, use pyftfeatfreeze to permanently activate tnum,
it causes some weirdly large white spaces in surrounding text (especially in weights 400 to below).

**To Reproduce**
1. Download Inter from this repository
2. With pyftfeatfreeze, embed tnum feature
3. You will see, in texts that use hyphen, that there will be some weirdly wide white spaces

**Expected behavior**
These white spaces mentioned in OP should, at least, be lessened

**Screenshots**
This is "Lê-se" (Portuguese for "It reads") in Display Thin.
![Captura de tela 2024-09-09 180823](https://github.com/user-attachments/assets/d3985539-8abc-4b4b-ba09-c3ea55afefd5)
As you can see above, the hyphen in tnum is so overspaced that the text above can be confused with "Lê - se" (as if there
it were actual spaces in-between).

**Environment**
- This is glyph-level, so every app/OS display this issue
- Version 4.0 (the latest in this repo)

**Additional context**
A suggestion about this is reducing hyphen.tf/hyphen.case.tf advance width to 1000.

**Comment by rsms** [comment]
This is by design. The width must be uniform across all designs for tnum to allow mixing styles while maintaining column alignment. For example:

<img width="1683" alt="Screen Shot 2024-11-15 at 14 50 41" src="https://github.com/user-attachments/assets/889b552e-be79-48c9-b316-ead27f5bcb76">

I recommend using tnum only for tabular data. Don't enable it carte blanche
