### ISSUE TITLE
Feature option to disable humanist style

### ISSUE THREAD

**Issue by Seb33300** [rsms/inter#755]
Hello,

In our web project, we do not want to use the _humanist style_ added to some letters and unfortunately, it seems that there is no feature option to disable it.
Did I miss something or this is really not possible to disable it?

If it not possible to disable it, is it possible to load a previous version of the front from your CDN?
I can only find the URL to load the latest version.

Thank you

**Comment by rsms** [comment]
You can't "disable it" because that's the way it's designed.
You have two options:
1. Fork Inter and replace glyphs like /f with your own preferred design
2. Use faux oblique by having your software (eg. web browser) sheer the shapes of the regular roman fonts. This will not look great but perhaps it will be adequate for your needs.

In the future, follow the issue template for issues (to prevent from being banned) and do not file an issue when you have a question, instead use "Discussions" for questions

**Comment by Seb33300** [comment]
Hi @rsms,

FYI, I clicked on the `Feature request` button:

![image](https://github.com/user-attachments/assets/e1ee13fa-1916-4caa-a40f-0a79a5d9f994)
