### ISSUE TITLE
Weird opsz on opsz 14, wght 400 in Safari

### ISSUE THREAD

**Issue by quiple** [rsms/inter#765]
**Describe the bug**
I noticed some strange behavior in certain opsz and wght at https://rsms.me/inter/lab/.

https://github.com/user-attachments/assets/3357b238-7022-4a01-add0-7fb9220ad937

**To Reproduce**
The glyphs' optical size weird only on opsz 14, wght 400.

**Screenshots**
<img width="1640" alt="스크린샷 2024-11-16 12 53 42" src="https://github.com/user-attachments/assets/ae6eb77d-c983-4809-89a2-13c8a7029fae">

**Environment**
- OS: macOS 15.1
- Safari
- v4.1

**Comment by rsms** [comment]
Can you clarify *what* is wrong? (I can’t play the video)

**Comment by quiple** [comment]
@rsms Sorry for the lack of explanation. It looks like opsz 32 when the opsz is 14 and wght 400.

**Comment by rsms** [comment]
I think I understand. Can you please post complete minimal HTML/CSS for reproducing the issue?

**Comment by quiple** [comment]
@rsms Sorry, I realized after creating the HTML file, it seems to only happen in Safari, but it doesn't seem to happen in SF Pro.

[Test.zip](https://github.com/user-attachments/files/17793215/Test.zip)

**Comment by rsms** [comment]
Here's quiple's HTML (from the zip file)

```html
<style>
  @font-face {
    font-family: Inter3-19;
    font-weight: 100 900;
    src: url(./Inter3.19.woff2);
  }
  @font-face {
    font-family: Inter4-0;
    font-weight: 100 900;
    src: url(./Inter4.0.woff2);
  }
  @font-face {
    font-family: Inter4-1;
    font-weight: 100 900;
    src: url(./Inter4.1.woff2);
  }
  h1 { font-size: 4rem; font-variation-settings: 'opsz' 14, 'wght' 400; }
  .i3-19 { font-family: Inter3-19; }
  .i4 { font-family: Inter4-0; }
  .i4-1 { font-family: Inter4-1; }
  .sf { font-family: -apple-system, BlinkMacSystemFont; }
</style>
<h1 class="i3-19">v3.19, 1x1, opsz 14, wght 400</h1>
<h1 class="i4">v4.0, 1x1, opsz 14, wght 400</h1>
<h1 class="i4-1">v4.1, 1x1, opsz 14, wght 400</h1>
<h1 class="sf">SF Pro, 1x1, opsz 14, wght 400</h1>
```

**Comment by rsms** [comment]
Looks correct in Safari (17.5), Chrome and Firefox for me:

<img width="936" alt="Screen Shot 2024-11-18 at 18 10 35" src="https://github.com/user-attachments/assets/5af6ad70-19a3-4cf5-a3ac-1a80ae28ef0e">

<img width="969" alt="Screen Shot 2024-11-18 at 18 10 56" src="https://github.com/user-attachments/assets/cb5ba06b-1087-421e-9a77-ba4e2261c077">

<img width="972" alt="Screen Shot 2024-11-18 at 18 11 31" src="https://github.com/user-attachments/assets/991f3c39-f244-494a-983d-602d8789cd9f">

There have been an increase in regression bugs in macOS since version 11, so I'm not surprised to see this. My only recommendation is to use a different browser or switch to a less buggy version of macOS. I don't think there's anything _I_ can do about this.
