### ISSUE TITLE
Please put woff/woff2 variable fonts in the download package

### ISSUE THREAD

**Issue by code-mattclaffey** [rsms/inter#77]
I was trying to use this to measure the value of using this font instead of my current ones but whenever I tried to convert the **Inter-UI.var.ttf** file on Font Squirrel it only returned me the regular font weight of that variable font. 

It would be useful if this was already done in the other formats as 800kb+ ttf font file is very large. 

I also could not find any documentation around the variable font and how to use and what options it had. Could you point me in the right direction for this please? 

Thanks

Matt

**Comment by rsms** [comment]
What zip file did you download? Since you are not providing any information on what version or file you're talking about, I'm going to assume it's the latest pre-release "v3.0-rc2".

Both the [RC2](https://github.com/rsms/inter/releases/tag/v3.0-rc2) and the [RC1](https://github.com/rsms/inter/releases/tag/v3.0-rc1) release contains a variable version of the font in WOFF2 format.

<img width="812" alt="screen shot 2018-09-27 at 08 43 37" src="https://user-images.githubusercontent.com/47046/46157969-c212d400-c231-11e8-9202-a8137fcd5da7.png">

Note that WOFF (v1) is a legacy format and any browser that supports variable fonts also supports WOFF2, so there's no WOFF (v1) file.

Additionally, the "variable.txt" file has some information about the variable font, and inter-ui.css contains example code for how to use Inter UI both with constant/classic fallback font files as well as purely variable.

Please, in the future, use one of the issue templates when filing an issue (choose one of the two large buttons incstead of clickin the hyperlink saying "Open a regular issue." Thank you.
