### ISSUE TITLE
Improve prime glyphs

### ISSUE THREAD

**Issue by cssobral2013** [rsms/inter#86]
**Describe the bug**
As the glyph with Unicode map is missing in all 12 weights, texts in Greek cannot be fully rendered in this font.
**To Reproduce**
Just write any text in Greek language, as the aforementioned glyph is required in basic Greek.

**Expected behavior**
All texts in Greek should be rendering normally.

**Environment**
- OS: Debian 9.5 Stretch
- Any and all apps display that problem
- Version 3.0

---

[edit by rsms]

- Prime `U+2032`
- Double Prime `U+2033`
- Triple Prime `U+2034`
- Quadruple Prime `U+2057`

> "Really liking Inter UI, but noticed that prime, double prime, and triple prime aren't consistent. Personally I'd like to see them look a little more like something halfway between the apostrophe and right single quote. Maybe a slightly shorter version of the comma glyph?" — https://twitter.com/andykelly_/status/1053327060897284096

**Comment by rsms** [comment]
Note that Inter UI already contains the following glyphs with codepoint mappings:

- prime  `U+2032`
- doubleprime  `U+2033`
- tripleprime  `U+2034`
- primerev  `U+2035`
- doubleprimerev  `U+2036`
- tripleprimerev  `U+2037`
- quadrupleprime  `U+2057`
- doubleprimemod  `U+02BA`

I'm _improving_ these glyphs.

If your issue is about _missing_ glyphs, then I think you are either mistaken (maybe a different glyph that's missing?) or some bug/issue with the window manager you're using on Debian (I've got an Ubuntu machine and there are all sorts of font issues with all sorts of fonts on Linux for me.)

**Comment by rsms** [comment]
What it looks like at weight 600:
<img width="123" alt="screen shot 2018-11-24 at 13 08 34" src="https://user-images.githubusercontent.com/47046/48972957-134d0300-efea-11e8-85cc-20f1b2c729a6.png">
